export const COURT_TYPES = [
  'Supreme Court of India',
  'High Court',
  'District Court',
  'District & Sessions Court',
  'Civil Court',
  'Senior Civil Judge Court',
  'Junior Civil Judge Court',
  'Judicial Magistrate First Class (JMFC)',
  'Chief Judicial Magistrate (CJM)',
  'Metropolitan Magistrate',
  'Family Court',
  'Juvenile Justice Board',
  'Labour Court',
  'Industrial Tribunal',
  'Commercial Court',
  'Small Causes Court',
  'Consumer Commission (District)',
  'Consumer Commission (State)',
  'Consumer Commission (National)',
  'Motor Accident Claims Tribunal (MACT)',
  'Debt Recovery Tribunal (DRT)',
  'Debt Recovery Appellate Tribunal (DRAT)',
  'Central Administrative Tribunal (CAT)',
  'National Company Law Tribunal (NCLT)',
  'National Company Law Appellate Tribunal (NCLAT)',
  'Income Tax Appellate Tribunal (ITAT)',
  'National Green Tribunal (NGT)',
  'Real Estate Regulatory Authority (RERA)',
  'Electricity Appellate Tribunal',
  'Arbitration Tribunal',
  'Lok Adalat',
  'Permanent Lok Adalat',
  'Gram Nyayalaya',
  'Revenue Court',
  'Cooperative Court',
  'Customs Tribunal',
  'GST Tribunal',
  'Cyber Tribunal',
  'Special CBI Court',
  'Special POCSO Court',
  'Special NDPS Court',
  'Special Fast Track Court',
  'Military Tribunal',
  'Election Tribunal',
  'Tribunal (Other)',
  'Other'
];
