/**
 * AI Legal Mobile - Legal Templates Registry Data
 * Contains a comprehensive list of 91 legal templates grouped by Indian practice areas,
 * along with search keywords, difficulty ratings, estimated drafting times, and field structures.
 */

export interface FormField {
  key: string;
  label: string;
  type: 'text' | 'multiline' | 'number' | 'date' | 'select' | 'email' | 'phone';
  required: boolean;
  placeholder?: string;
  options?: string[];
  hint?: string;
}

export interface TemplateMetadata {
  id: string;
  title: string;
  description: string;
  icon: string;
  category: 'Civil' | 'Criminal' | 'Corporate' | 'Property' | 'Family' | 'Employment' | 'Banking' | 'Consumer' | 'Contracts' | 'Court Pleadings' | 'Affidavits' | 'Miscellaneous';
  estimatedTime: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  rating: number; // 1 to 5 stars
  aiReady: boolean;
  keywords: string[];
  fields?: FormField[]; // Specific fields, otherwise fall back to category default fields
}

// Category fallback fields to ensure all 91 templates have rich inputs without duplicating declarations
export const CATEGORY_DEFAULT_FIELDS: Record<string, FormField[]> = {
  'Civil': [
    { key: 'petitionerName', label: 'Petitioner / Plaintiff Name', type: 'text', required: true, placeholder: 'e.g. Amit Sen' },
    { key: 'petitionerAddress', label: 'Petitioner Address', type: 'text', required: true, placeholder: 'e.g. Sector 12, Dwarka, Delhi' },
    { key: 'respondentName', label: 'Respondent / Defendant Name', type: 'text', required: true, placeholder: 'e.g. Vijay Verma' },
    { key: 'respondentAddress', label: 'Respondent Address', type: 'text', required: true, placeholder: 'e.g. Sector 4, Rohini, Delhi' },
    { key: 'courtName', label: 'Court Name', type: 'text', required: true, placeholder: 'e.g. District Court, Saket' },
    { key: 'caseDetails', label: 'Brief Facts of Case', type: 'multiline', required: true, placeholder: 'Explain the civil dispute facts...' },
    { key: 'reliefSought', label: 'Relief / Prayer Sought', type: 'multiline', required: true, placeholder: 'Describe what you want the court to order...' },
    { key: 'jurisdiction', label: 'Jurisdiction Court Limits', type: 'text', required: true, placeholder: 'e.g. Delhi Courts' },
  ],
  'Criminal': [
    { key: 'complainantName', label: 'Complainant / Petitioner Name', type: 'text', required: true, placeholder: 'e.g. Suresh Prasad' },
    { key: 'complainantAddress', label: 'Complainant Address', type: 'text', required: true, placeholder: 'e.g. B-40, Saket, Delhi' },
    { key: 'accusedName', label: 'Accused Name (if known)', type: 'text', required: false, placeholder: 'e.g. Unknown / Ramesh Rao' },
    { key: 'policeStation', label: 'Local Police Station Name', type: 'text', required: true, placeholder: 'e.g. Saket Police Station' },
    { key: 'incidentDate', label: 'Incident Date', type: 'date', required: true, placeholder: 'YYYY-MM-DD' },
    { key: 'incidentDescription', label: 'Incident Description', type: 'multiline', required: true, placeholder: 'Describe the criminal offence in detail...' },
    { key: 'reliefRequested', label: 'Relief / Action Requested', type: 'text', required: true, placeholder: 'e.g. Arrest of accused and registration of FIR' },
  ],
  'Corporate': [
    { key: 'companyName', label: 'Company / Firm Name', type: 'text', required: true, placeholder: 'e.g. LexCorp Tech Private Limited' },
    { key: 'registeredOffice', label: 'Registered Office Address', type: 'text', required: true, placeholder: 'e.g. Connaught Place, New Delhi' },
    { key: 'meetingDate', label: 'Meeting / Resolution Date', type: 'date', required: true, placeholder: 'YYYY-MM-DD' },
    { key: 'chairpersonName', label: 'Chairperson / Director Name', type: 'text', required: true, placeholder: 'e.g. Devendra Singh' },
    { key: 'agenda', label: 'Agenda of Notice / Resolution', type: 'multiline', required: true, placeholder: 'Explain corporate decisions, share allocations, or items...' },
    { key: 'resolutionDetails', label: 'Resolution / Proposal Details', type: 'multiline', required: true, placeholder: 'Enter resolution details approved...' },
  ],
  'Property': [
    { key: 'transferorName', label: 'Transferor / Seller Name', type: 'text', required: true, placeholder: 'e.g. Rajendra Prasad' },
    { key: 'transfereeName', label: 'Transferee / Buyer Name', type: 'text', required: true, placeholder: 'e.g. Vikram Aditya' },
    { key: 'propertyDescription', label: 'Detailed Property Description', type: 'multiline', required: true, placeholder: 'Plot/Flat details, boundaries, dimensions...' },
    { key: 'considerationAmount', label: 'Sale Value / Consideration (INR)', type: 'number', required: true, placeholder: 'e.g. 5500000' },
    { key: 'keyTerms', label: 'Key Terms / Handover Dates', type: 'multiline', required: true, placeholder: 'Terms of sale, registry timelines, possession details...' },
    { key: 'witnessDetails', label: 'Witness Names & Details', type: 'text', required: false, placeholder: 'e.g. Witness A: R.K. Gupta, Witness B: S.K. Roy' },
  ],
  'Family': [
    { key: 'petitionerName', label: 'Petitioner / Spouse Name', type: 'text', required: true, placeholder: 'e.g. Priya Sharma' },
    { key: 'respondentName', label: 'Respondent / Spouse Name', type: 'text', required: true, placeholder: 'e.g. Anil Sharma' },
    { key: 'marriageDate', label: 'Marriage Solemnization Date', type: 'date', required: true, placeholder: 'YYYY-MM-DD' },
    { key: 'marriagePlace', label: 'Place of Marriage', type: 'text', required: true, placeholder: 'e.g. Jaipur, Rajasthan' },
    { key: 'facts', label: 'Crucial Facts / Matrimonial History', type: 'multiline', required: true, placeholder: 'Detail background, separation dates, disputes, children...' },
    { key: 'reliefRequested', label: 'Relief / Alimony Demanded', type: 'multiline', required: true, placeholder: 'Divorce decree, monthly maintenance of INR 30,000, child custody...' },
    { key: 'jurisdiction', label: 'Family Court Jurisdiction', type: 'text', required: true, placeholder: 'e.g. Family Court, Saket, Delhi' },
  ],
  'Employment': [
    { key: 'employerName', label: 'Employer / Company Name', type: 'text', required: true, placeholder: 'e.g. ABC Systems India Pvt Ltd' },
    { key: 'employeeName', label: 'Employee Full Name', type: 'text', required: true, placeholder: 'e.g. Rohan Das' },
    { key: 'jobTitle', label: 'Designation / Job Role', type: 'text', required: true, placeholder: 'e.g. Senior Software Engineer' },
    { key: 'joiningDate', label: 'Date of Joining / Start Date', type: 'date', required: true, placeholder: 'YYYY-MM-DD' },
    { key: 'compensation', label: 'Annual CTC / Salary (INR)', type: 'number', required: true, placeholder: 'e.g. 1200000' },
    { key: 'terminationTerms', label: 'Notice Period / Severance Terms', type: 'multiline', required: true, placeholder: 'e.g. 30 days notice or 1 month salary in lieu of notice...' },
  ],
  'Banking': [
    { key: 'borrowerName', label: 'Borrower Name', type: 'text', required: true, placeholder: 'e.g. G.S. Enterprises' },
    { key: 'lenderName', label: 'Lender / Bank Name', type: 'text', required: true, placeholder: 'e.g. State Bank of India' },
    { key: 'loanAmount', label: 'Principal Loan Amount (INR)', type: 'number', required: true, placeholder: 'e.g. 2500000' },
    { key: 'interestRate', label: 'Interest Rate per Annum (%)', type: 'text', required: true, placeholder: 'e.g. 9.5% p.a.' },
    { key: 'repaymentTerms', label: 'Repayment Schedule / Tenure', type: 'multiline', required: true, placeholder: 'e.g. 60 Equated Monthly Instalments (EMIs) of INR 52,000...' },
    { key: 'defaultClause', label: 'Default / Collateral Terms', type: 'multiline', required: true, placeholder: 'Consequences of default, mortgaged assets details...' },
  ],
  'Consumer': [
    { key: 'complainantName', label: 'Complainant Full Name', type: 'text', required: true, placeholder: 'e.g. Nitin Gupta' },
    { key: 'oppositeParty', label: 'Opposite Party (Vendor/Company)', type: 'text', required: true, placeholder: 'e.g. Prime Gadgets Retail Ltd' },
    { key: 'productService', label: 'Product or Service Details', type: 'text', required: true, placeholder: 'e.g. Premium Smart TV 55 inch' },
    { key: 'purchaseDate', label: 'Purchase/Order Date', type: 'date', required: true, placeholder: 'YYYY-MM-DD' },
    { key: 'grievance', label: 'Grievance / Defect Details', type: 'multiline', required: true, placeholder: 'Explain defect, service deficiency, customer support failure...' },
    { key: 'compensation', label: 'Compensation & Refund Demanded (INR)', type: 'number', required: true, placeholder: 'e.g. 75000' },
  ],
  'Contracts': [
    { key: 'party1', label: 'First Party Name', type: 'text', required: true, placeholder: 'e.g. ABC Solutions' },
    { key: 'party2', label: 'Second Party Name', type: 'text', required: true, placeholder: 'e.g. XYZ Enterprises' },
    { key: 'purpose', label: 'Purpose of Agreement', type: 'multiline', required: true, placeholder: 'Define contract scope and objectives...' },
    { key: 'keyTerms', label: 'Primary Terms & Deliverables', type: 'multiline', required: true, placeholder: 'Milestones, payments, timelines, deliverables...' },
    { key: 'duration', label: 'Effective Duration', type: 'text', required: true, placeholder: 'e.g. 1 Year from execution date' },
    { key: 'jurisdiction', label: 'Governing Law & Courts', type: 'text', required: true, placeholder: 'e.g. Courts at New Delhi' },
  ],
  'Court Pleadings': [
    { key: 'courtName', label: 'Honorable Court Name', type: 'text', required: true, placeholder: 'e.g. High Court of Delhi' },
    { key: 'caseNumber', label: 'Case Number (if registered)', type: 'text', required: false, placeholder: 'e.g. Arb. P. 104/2026' },
    { key: 'petitioner', label: 'Petitioner / Appellant Name', type: 'text', required: true, placeholder: 'e.g. ABC Enterprises' },
    { key: 'respondent', label: 'Respondent Name', type: 'text', required: true, placeholder: 'e.g. Government of NCT' },
    { key: 'facts', label: 'Grounds & Material Facts', type: 'multiline', required: true, placeholder: 'Detail chronological facts of appeal, revision, or petition...' },
    { key: 'prayer', label: 'Prayer / Order Sought', type: 'multiline', required: true, placeholder: 'Plea / Order requested from the Honorable Court...' },
  ],
  'Affidavits': [
    { key: 'deponentName', label: 'Deponent Full Name', type: 'text', required: true, placeholder: 'e.g. Priya Sharma' },
    { key: 'guardianName', label: "Deponent's Father / Spouse Name", type: 'text', required: true, placeholder: 'e.g. Anil Sharma' },
    { key: 'deponentAddress', label: 'Deponent Address', type: 'text', required: true, placeholder: 'e.g. C-15, GK, Delhi' },
    { key: 'purpose', label: 'Purpose of Swearing Affidavit', type: 'text', required: true, placeholder: 'e.g. Verification of identity / Name change' },
    { key: 'declarations', label: 'Declarations (Point by Point)', type: 'multiline', required: true, placeholder: '1. I state that my correct name is Priya...\n2. I state that...' },
    { key: 'verificationPlace', label: 'Verification Place', type: 'text', required: true, placeholder: 'e.g. New Delhi' },
  ],
  'Miscellaneous': [
    { key: 'docTitle', label: 'Document Title', type: 'text', required: true, placeholder: 'e.g. Chronology of Events' },
    { key: 'parties', label: 'Parties Involved', type: 'text', required: true, placeholder: 'e.g. Client A vs Respondent B' },
    { key: 'purpose', label: 'Document Objective', type: 'multiline', required: true, placeholder: 'Background / Context of this compilation...' },
    { key: 'details', label: 'Content Details / Facts', type: 'multiline', required: true, placeholder: 'List out specific points, chronology, opinions, or details...' },
  ]
};

export const ALL_TEMPLATES: TemplateMetadata[] = [
  // ================= LEGAL NOTICES (13 templates) =================
  {
    id: 'legalNotice',
    title: 'Legal Notice',
    description: 'Formal legal notices demanding compliance, payments, or actions from an opposing party.',
    icon: 'mail-open-outline',
    category: 'Miscellaneous', // Keep as notices but categorized appropriately
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 5,
    aiReady: true,
    keywords: ['notice', 'legal notice', 'civil notice', 'pre-action notice'],
    fields: [
      { key: 'senderName', label: 'Sender Name', type: 'text', required: true, placeholder: 'e.g. ABC Tech Solutions' },
      { key: 'senderAddress', label: 'Sender Address', type: 'text', required: true, placeholder: 'e.g. 504, Nehru Place, Delhi' },
      { key: 'receiverName', label: 'Receiver Name (Opponent)', type: 'text', required: true, placeholder: 'e.g. XYZ Enterprises' },
      { key: 'receiverAddress', label: 'Receiver Address', type: 'text', required: true, placeholder: 'e.g. Plot 12, Phase 3, Noida' },
      { key: 'subject', label: 'Subject of Legal Notice', type: 'text', required: true, placeholder: 'e.g. Notice for Recovery of Outstanding Dues' },
      { key: 'facts', label: 'Facts of the Matter', type: 'multiline', required: true, placeholder: 'Explain the background, dates, agreements, and breach...' },
      { key: 'grounds', label: 'Legal Grounds / Violation sections', type: 'multiline', required: true, placeholder: 'e.g. Violation of Section 73 of Indian Contract Act...' },
      { key: 'reliefRequested', label: 'Action/Relief Demanded', type: 'text', required: true, placeholder: 'e.g. Pay outstanding amount of INR 5,00,000' },
      { key: 'compliancePeriod', label: 'Compliance Time Limit', type: 'select', required: true, options: ['15 Days', '30 Days', '45 Days'], placeholder: 'Select limit' },
      { key: 'jurisdiction', label: 'Court Jurisdiction', type: 'text', required: true, placeholder: 'e.g. Courts of Delhi' },
    ]
  },
  {
    id: 'demandNotice',
    title: 'Demand Notice',
    description: 'Notice for payment or performance of an obligation, raising official commercial claims.',
    icon: 'cash-outline',
    category: 'Banking',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 4.8,
    aiReady: true,
    keywords: ['notice', 'demand notice', 'outstanding payment', 'remittance demand'],
  },
  {
    id: 'recoveryNotice',
    title: 'Recovery Notice',
    description: 'Legal warning to recover outstanding debts, payments, or loans prior to civil lawsuit.',
    icon: 'wallet-outline',
    category: 'Banking',
    estimatedTime: '3 Minutes',
    difficulty: 'Easy',
    rating: 4.9,
    aiReady: true,
    keywords: ['notice', 'recovery notice', 'debt recovery', 'money collection', 'default payment'],
  },
  {
    id: 'showCauseNotice',
    title: 'Show Cause Notice',
    description: 'Official notice demanding explanation for misconduct, defaults, or regulatory breaches.',
    icon: 'help-circle-outline',
    category: 'Miscellaneous',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 4.5,
    aiReady: true,
    keywords: ['notice', 'show cause notice', 'scn', 'explanation demand', 'disciplinary notice'],
  },
  {
    id: 'evictionNotice',
    title: 'Eviction Notice',
    description: 'Landlord notice demanding tenant vacate premises due to lease expiration or default.',
    icon: 'exit-outline',
    category: 'Property',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 4.7,
    aiReady: true,
    keywords: ['notice', 'eviction notice', 'tenant eviction', 'landlord notice', 'vacate premises'],
  },
  {
    id: 'breachOfContractNotice',
    title: 'Breach of Contract Notice',
    description: 'Notice served to notify a contracting party of specific contractual violations.',
    icon: 'alert-circle-outline',
    category: 'Contracts',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.9,
    aiReady: true,
    keywords: ['notice', 'breach of contract notice', 'agreement violation', 'contract breach'],
  },
  {
    id: 'defamationNotice',
    title: 'Defamation Notice',
    description: 'Cease and desist warning notice regarding defamatory remarks, statements, or publications.',
    icon: 'chatbubble-ellipses-outline',
    category: 'Civil',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.6,
    aiReady: true,
    keywords: ['notice', 'defamation notice', 'slander notice', 'libel notice', 'cease and desist'],
  },
  {
    id: 'copyrightNotice',
    title: 'Copyright Notice',
    description: 'Intellectual property notice demanding removal of unauthorized copyrighted materials.',
    icon: 'document-text-outline',
    category: 'Corporate',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 4.8,
    aiReady: true,
    keywords: ['notice', 'copyright notice', 'ipr notice', 'dmca notice', 'copyright infringement'],
  },
  {
    id: 'trademarkInfringementNotice',
    title: 'Trademark Infringement Notice',
    description: 'Legal notice demanding cessation of unauthorized brand name or trademark usage.',
    icon: 'shield-outline',
    category: 'Corporate',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.7,
    aiReady: true,
    keywords: ['notice', 'trademark infringement notice', 'brand protection', 'trademark violation'],
  },
  {
    id: 'chequeBounceNotice',
    title: 'Cheque Bounce Notice (Section 138 NI Act)',
    description: 'Statutory legal demand notice for dishonoured cheque claims under Negotiable Instruments Act.',
    icon: 'card-outline',
    category: 'Banking',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 5,
    aiReady: true,
    keywords: ['notice', 'cheque bounce notice', 'section 138', '138 ni act', 'negotiable instruments', 'dishonoured cheque'],
  },
  {
    id: 'consumerLegalNotice',
    title: 'Consumer Legal Notice',
    description: 'Formal complaint notice served on manufacturers or service providers for deficiency of service.',
    icon: 'cart-outline',
    category: 'Consumer',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 4.9,
    aiReady: true,
    keywords: ['notice', 'consumer legal notice', 'product defect notice', 'service deficiency notice'],
  },
  {
    id: 'employmentTerminationNotice',
    title: 'Employment Termination Notice',
    description: 'Corporate notice served to employees terminating their employment services.',
    icon: 'briefcase-outline',
    category: 'Employment',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 4.4,
    aiReady: true,
    keywords: ['notice', 'employment termination notice', 'firing notice', 'layoff notice', 'relieving notice'],
  },
  {
    id: 'rentDefaultNotice',
    title: 'Rent Default Notice',
    description: 'Formal landlord notice demanding payment of outstanding rental arrears from tenant.',
    icon: 'home-outline',
    category: 'Property',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 4.7,
    aiReady: true,
    keywords: ['notice', 'rent default notice', 'rental dues notice', 'lease default notice'],
  },

  // ================= CONTRACTS (15 templates) =================
  {
    id: 'rentAgreement',
    title: 'Rent Agreement',
    description: 'Residential or commercial lease deeds between landlord and tenant.',
    icon: 'home-outline',
    category: 'Contracts',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 5,
    aiReady: true,
    keywords: ['agreement', 'rent agreement', 'residential lease', 'commercial lease', 'tenancy contract'],
    fields: [
      { key: 'landlordName', label: 'Landlord Name', type: 'text', required: true, placeholder: 'e.g. Ramesh Kumar' },
      { key: 'landlordAddress', label: 'Landlord Address', type: 'text', required: true, placeholder: 'e.g. Flat 101, Sector 15, Delhi' },
      { key: 'tenantName', label: 'Tenant Name', type: 'text', required: true, placeholder: 'e.g. Vikram Aditya' },
      { key: 'tenantAddress', label: 'Tenant Address', type: 'text', required: true, placeholder: 'e.g. H-12, Sector 2, Delhi' },
      { key: 'propertyAddress', label: 'Property Address to Lease', type: 'text', required: true, placeholder: 'e.g. Flat 302, Pocket B, Delhi' },
      { key: 'monthlyRent', label: 'Monthly Rent Amount (INR)', type: 'number', required: true, placeholder: 'e.g. 15000' },
      { key: 'securityDeposit', label: 'Security Deposit Amount (INR)', type: 'number', required: true, placeholder: 'e.g. 30000' },
      { key: 'startDate', label: 'Agreement Start Date', type: 'date', required: true, placeholder: 'YYYY-MM-DD' },
      { key: 'duration', label: 'Agreement Duration', type: 'select', required: true, options: ['11 Months', '1 Year', '2 Years', '3 Years'], placeholder: 'Select duration' },
      { key: 'noticePeriod', label: 'Notice Period required', type: 'select', required: true, options: ['1 Month', '2 Months', '3 Months'], placeholder: 'Select notice period' },
      { key: 'maintenance', label: 'Maintenance Responsibility', type: 'select', required: true, options: ['Landlord', 'Tenant', 'Shared'], placeholder: 'Select responsibility' },
      { key: 'jurisdiction', label: 'Governing Jurisdiction / Court', type: 'text', required: true, placeholder: 'e.g. Delhi Courts' },
    ]
  },
  {
    id: 'leaseAgreement',
    title: 'Lease Agreement',
    description: 'Long-term commercial or residential property lease agreements with detailed provisions.',
    icon: 'key-outline',
    category: 'Contracts',
    estimatedTime: '4 Minutes',
    difficulty: 'Medium',
    rating: 4.8,
    aiReady: true,
    keywords: ['agreement', 'lease agreement', 'commercial lease', 'long term lease', 'property lease'],
  },
  {
    id: 'saleAgreement',
    title: 'Sale Agreement',
    description: 'Agreement to sell property detailing payment terms, consideration, and handover schedule.',
    icon: 'document-text-outline',
    category: 'Contracts',
    estimatedTime: '4 Minutes',
    difficulty: 'Medium',
    rating: 4.9,
    aiReady: true,
    keywords: ['agreement', 'sale agreement', 'property sale', 'real estate sale contract', 'purchase agreement'],
  },
  {
    id: 'employmentAgreement',
    title: 'Employment Agreement',
    description: 'Comprehensive employment terms, employee benefits, code of conduct, and job roles contract.',
    icon: 'briefcase-outline',
    category: 'Employment',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.8,
    aiReady: true,
    keywords: ['agreement', 'employment agreement', 'job contract', 'work terms agreement'],
  },
  {
    id: 'serviceAgreement',
    title: 'Service Agreement',
    description: 'Service level agreement (SLA) contract between service provider and corporate client.',
    icon: 'construct-outline',
    category: 'Contracts',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.9,
    aiReady: true,
    keywords: ['agreement', 'service agreement', 'sla contract', 'service provider agreement'],
  },
  {
    id: 'consultancyAgreement',
    title: 'Consultancy Agreement',
    description: 'Agreement appointing external consultants detailing milestones, fees, and scopes.',
    icon: 'people-outline',
    category: 'Contracts',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.7,
    aiReady: true,
    keywords: ['agreement', 'consultancy agreement', 'consultant contract', 'professional services agreement'],
  },
  {
    id: 'vendorAgreement',
    title: 'Vendor Agreement',
    description: 'Supply chain vendor contract detailing product delivery specifications, pricing, and terms.',
    icon: 'bus-outline',
    category: 'Contracts',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.8,
    aiReady: true,
    keywords: ['agreement', 'vendor agreement', 'supply contract', 'merchant service agreement'],
  },
  {
    id: 'partnershipDeed',
    title: 'Partnership Deed',
    description: 'Statutory deed to establish a partnership firm, detailing profit shares and capital ratios.',
    icon: 'people-circle-outline',
    category: 'Corporate',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.9,
    aiReady: true,
    keywords: ['agreement', 'partnership deed', 'firm creation deed', 'partnership terms'],
  },
  {
    id: 'nda',
    title: 'NDA (Non-Disclosure Agreement)',
    description: 'Mutual or one-way confidentiality agreement restricting sharing of intellectual data.',
    icon: 'lock-closed-outline',
    category: 'Contracts',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 5,
    aiReady: true,
    keywords: ['agreement', 'nda', 'non-disclosure agreement', 'confidentiality contract'],
  },
  {
    id: 'mou',
    title: 'MoU (Memorandum of Understanding)',
    description: 'Non-binding or semi-binding initial agreement establishing intent of collaboration.',
    icon: 'hand-left-outline',
    category: 'Contracts',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.8,
    aiReady: true,
    keywords: ['agreement', 'mou', 'memorandum of understanding', 'preliminary contract'],
  },
  {
    id: 'franchiseAgreement',
    title: 'Franchise Agreement',
    description: 'Agreement for licensing business models, trademarks, and operations to a franchisee.',
    icon: 'business-outline',
    category: 'Contracts',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.7,
    aiReady: true,
    keywords: ['agreement', 'franchise agreement', 'brand licensing', 'franchise contract'],
  },
  {
    id: 'loanAgreement',
    title: 'Loan Agreement',
    description: 'Personal or commercial loan contract detailing interest, default clauses, and EMI schedules.',
    icon: 'cash-outline',
    category: 'Banking',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.9,
    aiReady: true,
    keywords: ['agreement', 'loan agreement', 'debt contract', 'lending terms agreement'],
  },
  {
    id: 'giftDeed',
    title: 'Gift Deed',
    description: 'Legal deed transferring property ownership voluntarily without financial consideration.',
    icon: 'gift-outline',
    category: 'Property',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.8,
    aiReady: true,
    keywords: ['agreement', 'gift deed', 'voluntary transfer deed', 'property gift contract'],
  },
  {
    id: 'mortgageAgreement',
    title: 'Mortgage Agreement',
    description: 'Property mortgaging agreement detailing loan collateral terms, defaults, and foreclosures.',
    icon: 'home-outline',
    category: 'Banking',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.7,
    aiReady: true,
    keywords: ['agreement', 'mortgage agreement', 'property mortgage', 'collateral deed'],
  },
  {
    id: 'powerPurchaseAgreement',
    title: 'Power Purchase Agreement (PPA)',
    description: 'Commercial contract for purchase of energy/power, specifying rates, quotas, and terms.',
    icon: 'flash-outline',
    category: 'Contracts',
    estimatedTime: '5 Minutes',
    difficulty: 'Hard',
    rating: 4.6,
    aiReady: true,
    keywords: ['agreement', 'power purchase agreement', 'ppa', 'energy supply contract'],
  },

  // ================= COURT PLEADINGS (15 templates) =================
  {
    id: 'plaint',
    title: 'Plaint',
    description: 'Primary pleading document filed by the plaintiff to institute a civil suit in court.',
    icon: 'document-text-outline',
    category: 'Court Pleadings',
    estimatedTime: '5 Minutes',
    difficulty: 'Hard',
    rating: 5,
    aiReady: true,
    keywords: ['pleading', 'plaint', 'civil suit filing', 'lawsuit petition', 'instituting suit'],
  },
  {
    id: 'writtenStatement',
    title: 'Written Statement',
    description: 'Defense reply pleading filed by the defendant in response to the plaint summons.',
    icon: 'document-outline',
    category: 'Court Pleadings',
    estimatedTime: '5 Minutes',
    difficulty: 'Hard',
    rating: 4.9,
    aiReady: true,
    keywords: ['pleading', 'written statement', 'ws', 'defense reply', 'defendant response'],
  },
  {
    id: 'counterClaim',
    title: 'Counter Claim',
    description: 'Independent claim raised by the defendant against the plaintiff within the same suit.',
    icon: 'arrow-undo-outline',
    category: 'Court Pleadings',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.7,
    aiReady: true,
    keywords: ['pleading', 'counter claim', 'defendant counter lawsuit', 're-claim'],
  },
  {
    id: 'replication',
    title: 'Replication',
    description: 'Pleading response filed by the plaintiff answering the allegations inside the written statement.',
    icon: 'repeat-outline',
    category: 'Court Pleadings',
    estimatedTime: '4 Minutes',
    difficulty: 'Medium',
    rating: 4.8,
    aiReady: true,
    keywords: ['pleading', 'replication', 'rejoinder', 'plaintiff reply to ws'],
  },
  {
    id: 'civilAppeal',
    title: 'Civil Appeal',
    description: 'Appeal petition filed in higher courts against an adverse civil decree or judgment.',
    icon: 'trending-up-outline',
    category: 'Court Pleadings',
    estimatedTime: '5 Minutes',
    difficulty: 'Hard',
    rating: 4.9,
    aiReady: true,
    keywords: ['pleading', 'civil appeal', 'appeal petition', 'civil decree appeal'],
  },
  {
    id: 'criminalAppeal',
    title: 'Criminal Appeal',
    description: 'Appeal petition contesting an adverse conviction order in criminal trials.',
    icon: 'trending-up-outline',
    category: 'Court Pleadings',
    estimatedTime: '5 Minutes',
    difficulty: 'Hard',
    rating: 4.9,
    aiReady: true,
    keywords: ['pleading', 'criminal appeal', 'appeal against conviction', 'jail appeal'],
  },
  {
    id: 'revisionPetition',
    title: 'Revision Petition',
    description: 'Revision plea asking higher courts to examine judicial records for procedural errors.',
    icon: 'refresh-outline',
    category: 'Court Pleadings',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.8,
    aiReady: true,
    keywords: ['pleading', 'revision petition', 'civil revision', 'criminal revision'],
  },
  {
    id: 'reviewPetition',
    title: 'Review Petition',
    description: 'Plea to the court to review its own judgment due to errors apparent on face of record.',
    icon: 'eye-outline',
    category: 'Court Pleadings',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.7,
    aiReady: true,
    keywords: ['pleading', 'review petition', 'judgment review plea', 'court review'],
  },
  {
    id: 'specialLeavePetition',
    title: 'Special Leave Petition (SLP)',
    description: 'Special petition to approach the Honorable Supreme Court of India under Article 136.',
    icon: 'ribbon-outline',
    category: 'Court Pleadings',
    estimatedTime: '6 Minutes',
    difficulty: 'Hard',
    rating: 5,
    aiReady: true,
    keywords: ['pleading', 'slp', 'special leave petition', 'supreme court appeal', 'article 136'],
  },
  {
    id: 'transferPetition',
    title: 'Transfer Petition',
    description: 'Petition to transfer case proceedings from one state court/district to another.',
    icon: 'swap-horizontal-outline',
    category: 'Court Pleadings',
    estimatedTime: '4 Minutes',
    difficulty: 'Medium',
    rating: 4.6,
    aiReady: true,
    keywords: ['pleading', 'transfer petition', 'moving case petition', 'case transfer plea'],
  },
  {
    id: 'caveatPetition',
    title: 'Caveat Petition',
    description: 'Precautionary petition filed to prevent ex-parte orders without notifying the caveator.',
    icon: 'warning-outline',
    category: 'Court Pleadings',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.8,
    aiReady: true,
    keywords: ['pleading', 'caveat petition', 'caveat filing', 'pre-emptive plea'],
  },
  {
    id: 'executionPetition',
    title: 'Execution Petition',
    description: 'Application to enforce a court decree or judgment against the judgment debtor.',
    icon: 'checkmark-done-outline',
    category: 'Court Pleadings',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.7,
    aiReady: true,
    keywords: ['pleading', 'execution petition', 'enforcing decree', 'judgment execution'],
  },
  {
    id: 'interimApplication',
    title: 'Interim Application',
    description: 'Interlocutory application (IA) seeking temporary directives during suit pendency.',
    icon: 'hourglass-outline',
    category: 'Court Pleadings',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.8,
    aiReady: true,
    keywords: ['pleading', 'interim application', 'ia filing', 'interlocutory application'],
  },
  {
    id: 'stayApplication',
    title: 'Stay Application',
    description: 'Application seeking stay of execution or temporary injunction orders.',
    icon: 'pause-outline',
    category: 'Court Pleadings',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 5,
    aiReady: true,
    keywords: ['pleading', 'stay application', 'stay of order', 'temporary injunction plea', 'restraining order'],
  },
  {
    id: 'delayCondonationApplication',
    title: 'Delay Condonation Application',
    description: 'Application requesting the court to excuse a filing delay under Section 5 Limitation Act.',
    icon: 'time-outline',
    category: 'Court Pleadings',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.8,
    aiReady: true,
    keywords: ['pleading', 'delay condonation application', 'excuse limitation delay', 'section 5 limitation'],
  },

  // ================= CRIMINAL (8 templates) =================
  {
    id: 'fir',
    title: 'First Information Report (FIR)',
    description: 'Draft complaints for criminal offenses to be filed at local police stations.',
    icon: 'alert-circle-outline',
    category: 'Criminal',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 5,
    aiReady: true,
    keywords: ['criminal', 'fir', 'first information report', 'police complaint', 'reporting offense'],
    fields: [
      { key: 'policeStation', label: 'Police Station Name', type: 'text', required: true, placeholder: 'e.g. Saket Police Station' },
      { key: 'complainantName', label: 'Complainant Full Name', type: 'text', required: true, placeholder: 'e.g. Suresh Prasad' },
      { key: 'guardianName', label: "Father's / Husband's Name", type: 'text', required: true, placeholder: 'e.g. Om Prasad' },
      { key: 'complainantAddress', label: 'Contact Address', type: 'text', required: true, placeholder: 'e.g. B-40, Saket, Delhi' },
      { key: 'complainantPhone', label: 'Mobile Number', type: 'phone', required: true, placeholder: '10-digit number' },
      { key: 'incidentDate', label: 'Incident Date', type: 'date', required: true, placeholder: 'YYYY-MM-DD' },
      { key: 'incidentTime', label: 'Incident Time', type: 'text', required: true, placeholder: 'e.g. Around 4:30 PM' },
      { key: 'incidentLocation', label: 'Incident Location', type: 'text', required: true, placeholder: 'e.g. Saket Metro Market, Delhi' },
      { key: 'accusedName', label: 'Accused Name (if known)', type: 'text', required: false, placeholder: 'e.g. Unknown' },
      { key: 'incidentDescription', label: 'Description of Incident', type: 'multiline', required: true, placeholder: 'Describe the series of events in detail...' },
      { key: 'evidence', label: 'Evidence Available (if any)', type: 'text', required: false, placeholder: 'e.g. CCTV Footage, Phone Logs' },
      { key: 'reliefRequested', label: 'Relief/Action Requested', type: 'text', required: true, placeholder: 'e.g. Request to register FIR and recover stolen items' },
    ]
  },
  {
    id: 'criminalComplaint',
    title: 'Criminal Complaint',
    description: 'Private criminal complaint filed directly to Magistrates under Section 200 CrPC.',
    icon: 'document-text-outline',
    category: 'Criminal',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.8,
    aiReady: true,
    keywords: ['criminal', 'criminal complaint', 'section 200 crpc', 'private complaint to magistrate'],
  },
  {
    id: 'bailApplication',
    title: 'Bail Application',
    description: 'Regular bail application filed in trials under Section 437/439 of CrPC.',
    icon: 'key-outline',
    category: 'Criminal',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 5,
    aiReady: true,
    keywords: ['criminal', 'bail application', 'section 439 crpc', 'release application', 'regular bail'],
  },
  {
    id: 'anticipatoryBail',
    title: 'Anticipatory Bail',
    description: 'Pre-arrest bail application filed under Section 438 of CrPC in anticipation of arrest.',
    icon: 'shield-checkmark-outline',
    category: 'Criminal',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 5,
    aiReady: true,
    keywords: ['criminal', 'anticipatory bail', 'section 438 crpc', 'pre arrest bail plea'],
  },
  {
    id: 'quashingPetition',
    title: 'Quashing Petition',
    description: 'Petition to quash FIR or proceedings under Section 482 of CrPC in High Courts.',
    icon: 'trash-outline',
    category: 'Criminal',
    estimatedTime: '5 Minutes',
    difficulty: 'Hard',
    rating: 4.9,
    aiReady: true,
    keywords: ['criminal', 'quashing petition', 'section 482 crpc', 'quash fir proceedings'],
  },
  {
    id: 'protestPetition',
    title: 'Protest Petition',
    description: 'Petition challenging closure/final reports submitted by police in criminal investigations.',
    icon: 'alert-outline',
    category: 'Criminal',
    estimatedTime: '4 Minutes',
    difficulty: 'Medium',
    rating: 4.7,
    aiReady: true,
    keywords: ['criminal', 'protest petition', 'objecting final closure report', 'oppose police report'],
  },
  {
    id: 'dischargeApplication',
    title: 'Discharge Application',
    description: 'Plea to discharge the accused before charges are framed by the trial court.',
    icon: 'log-out-outline',
    category: 'Criminal',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.8,
    aiReady: true,
    keywords: ['criminal', 'discharge application', 'discharge plea', 'claim charge sheets insufficient'],
  },
  {
    id: 'compoundingPetition',
    title: 'Compounding Petition',
    description: 'Application for compounding compoundable offences, finalizing compromises.',
    icon: 'git-compare-outline',
    category: 'Criminal',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.6,
    aiReady: true,
    keywords: ['criminal', 'compounding petition', 'compounding offences', 'compromise plea'],
  },

  // ================= AFFIDAVITS (6 templates) =================
  {
    id: 'affidavit',
    title: 'General Affidavit',
    description: 'Sworn oath declarations to prove facts before legal or administrative authorities.',
    icon: 'document-text-outline',
    category: 'Affidavits',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 5,
    aiReady: true,
    keywords: ['affidavit', 'general affidavit', 'sworn declaration', 'self oath certificate'],
    fields: [
      { key: 'deponentName', label: 'Deponent Full Name', type: 'text', required: true, placeholder: 'e.g. Priya Sharma' },
      { key: 'guardianName', label: "Father's / Husband's Name", type: 'text', required: true, placeholder: 'e.g. Anil Sharma' },
      { key: 'deponentAddress', label: 'Residential Address', type: 'text', required: true, placeholder: 'e.g. C-15, GK, Delhi' },
      { key: 'deponentOccupation', label: 'Occupation', type: 'text', required: true, placeholder: 'e.g. Business Executive' },
      { key: 'purpose', label: 'Purpose of Affidavit', type: 'text', required: true, placeholder: 'e.g. Application for Name change' },
      { key: 'declarations', label: 'Declaration Statements (One per point)', type: 'multiline', required: true, placeholder: '1. I state that I have changed my name...\n2. I state that...' },
      { key: 'verificationPlace', label: 'Place of Verification', type: 'text', required: true, placeholder: 'e.g. New Delhi' },
    ]
  },
  {
    id: 'nameChangeAffidavit',
    title: 'Name Change Affidavit',
    description: 'Sworn affidavit verifying name change for gazette publication and updates.',
    icon: 'person-outline',
    category: 'Affidavits',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 4.8,
    aiReady: true,
    keywords: ['affidavit', 'name change affidavit', 'alias declaration', 'gazette name change'],
  },
  {
    id: 'addressProofAffidavit',
    title: 'Address Proof Affidavit',
    description: 'Affidavit declaring correct address details in absence of corporate address proof.',
    icon: 'navigate-outline',
    category: 'Affidavits',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 4.7,
    aiReady: true,
    keywords: ['affidavit', 'address proof affidavit', 'residency declaration', 'home address proof'],
  },
  {
    id: 'incomeAffidavit',
    title: 'Income Affidavit',
    description: 'Affidavit confirming annual income metrics for fee concessions or schemes.',
    icon: 'cash-outline',
    category: 'Affidavits',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 4.8,
    aiReady: true,
    keywords: ['affidavit', 'income affidavit', 'salary declaration', 'family income declaration'],
  },
  {
    id: 'marriageAffidavit',
    title: 'Marriage Affidavit',
    description: 'Joint declaration by spouses confirming marriage dates, places, and rituals.',
    icon: 'heart-outline',
    category: 'Affidavits',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 4.9,
    aiReady: true,
    keywords: ['affidavit', 'marriage affidavit', 'marriage registration support', 'spouses declaration'],
  },
  {
    id: 'affidavitOfEvidence',
    title: 'Affidavit of Evidence',
    description: 'Sworn affidavit filed as examination-in-chief in civil proceedings.',
    icon: 'briefcase-outline',
    category: 'Affidavits',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.9,
    aiReady: true,
    keywords: ['affidavit', 'affidavit of evidence', 'examination in chief', 'evidence affidavit'],
  },

  // ================= PROPERTY (8 templates) =================
  {
    id: 'saleDeed',
    title: 'Sale Deed',
    description: 'Final conveyance deed conveying absolute property ownership to the buyer.',
    icon: 'document-text-outline',
    category: 'Property',
    estimatedTime: '5 Minutes',
    difficulty: 'Hard',
    rating: 4.9,
    aiReady: true,
    keywords: ['property', 'sale deed', 'conveyance deed', 'transfer ownership deed'],
  },
  {
    id: 'giftDeedProperty',
    title: 'Gift Deed',
    description: 'Property transfer deed by donor to donee without monetary transaction.',
    icon: 'gift-outline',
    category: 'Property',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.8,
    aiReady: true,
    keywords: ['property', 'gift deed', 'voluntary transfer deed'],
  },
  {
    id: 'partitionDeed',
    title: 'Partition Deed',
    description: 'Deed dividing joint family property holdings among legal co-owners.',
    icon: 'cut-outline',
    category: 'Property',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.9,
    aiReady: true,
    keywords: ['property', 'partition deed', 'property division deed', 'family property split'],
  },
  {
    id: 'relinquishmentDeed',
    title: 'Relinquishment Deed',
    description: 'Deed relinquishing rights in inherited property to other co-heirs.',
    icon: 'trending-down-outline',
    category: 'Property',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.8,
    aiReady: true,
    keywords: ['property', 'relinquishment deed', 'release deed', 'surrender property rights'],
  },
  {
    id: 'will',
    title: 'Will',
    description: 'Last will and testament outlining asset distributions after demise.',
    icon: 'ribbon-outline',
    category: 'Property',
    estimatedTime: '4 Minutes',
    difficulty: 'Medium',
    rating: 5,
    aiReady: true,
    keywords: ['property', 'will', 'last will and testament', 'succession plan'],
  },
  {
    id: 'rectificationDeed',
    title: 'Rectification Deed',
    description: 'Correction deed executed to rectify errors inside registered deeds.',
    icon: 'create-outline',
    category: 'Property',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.6,
    aiReady: true,
    keywords: ['property', 'rectification deed', 'correction deed', 'registered deed correction'],
  },
  {
    id: 'possessionLetter',
    title: 'Possession Letter',
    description: 'Letter issued confirming handover of property possession to buyer.',
    icon: 'mail-unread-outline',
    category: 'Property',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 4.7,
    aiReady: true,
    keywords: ['property', 'possession letter', 'handover letter', 'flat handover document'],
  },
  {
    id: 'propertyDeclaration',
    title: 'Property Declaration',
    description: 'Self-declaration declaring list of owned assets, lands, and investments.',
    icon: 'shield-outline',
    category: 'Property',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.5,
    aiReady: true,
    keywords: ['property', 'property declaration', 'asset declaration', 'list of assets statement'],
  },

  // ================= FAMILY (6 templates) =================
  {
    id: 'divorcePetition',
    title: 'Divorce Petition',
    description: 'Petition filed in Family Courts seeking judicial dissolution of marriage.',
    icon: 'heart-disliked-outline',
    category: 'Family',
    estimatedTime: '5 Minutes',
    difficulty: 'Hard',
    rating: 4.9,
    aiReady: true,
    keywords: ['family', 'divorce petition', 'contested divorce', 'marriage dissolution plea'],
  },
  {
    id: 'mutualDivorce',
    title: 'Mutual Divorce',
    description: 'Joint petition seeking mutual consent divorce under Section 13B Hindu Marriage Act.',
    icon: 'heart-half-outline',
    category: 'Family',
    estimatedTime: '4 Minutes',
    difficulty: 'Medium',
    rating: 5,
    aiReady: true,
    keywords: ['family', 'mutual divorce', 'section 13b hma', 'mutual consent divorce petition'],
  },
  {
    id: 'childCustodyPetition',
    title: 'Child Custody Petition',
    description: 'Petition seeking guardianship or custody rights of minor child in Family Court.',
    icon: 'people-outline',
    category: 'Family',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.8,
    aiReady: true,
    keywords: ['family', 'child custody petition', 'guardian appointment plea', 'custody rights'],
  },
  {
    id: 'maintenancePetition',
    title: 'Maintenance Petition',
    description: 'Plea seeking alimony or maintenance under Section 125 of CrPC.',
    icon: 'cash-outline',
    category: 'Family',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.8,
    aiReady: true,
    keywords: ['family', 'maintenance petition', 'section 125 crpc', 'monthly maintenance support', 'alimony plea'],
  },
  {
    id: 'domesticViolenceComplaint',
    title: 'Domestic Violence Complaint',
    description: 'Complaint seeking protection orders under Protection of Women from Domestic Violence Act.',
    icon: 'alert-outline',
    category: 'Family',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.9,
    aiReady: true,
    keywords: ['family', 'domestic violence complaint', 'dv complaint', 'protection order petition'],
  },
  {
    id: 'restitutionConjugalRights',
    title: 'Restitution of Conjugal Rights',
    description: 'Petition filed under Section 9 of the Hindu Marriage Act demanding cohabitation resumption.',
    icon: 'sync-outline',
    category: 'Family',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.6,
    aiReady: true,
    keywords: ['family', 'restitution of conjugal rights', 'section 9 hma', 'cohabitation plea'],
  },

  // ================= CONSUMER (3 templates) =================
  {
    id: 'consumerComplaint',
    title: 'Consumer Complaint',
    description: 'Intelligent legal complaints for consumer dispute redressal commissions.',
    icon: 'basket-outline',
    category: 'Consumer',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 5,
    aiReady: true,
    keywords: ['consumer', 'consumer complaint', 'deficiency of service', 'distrct consumer forum'],
    fields: [
      { key: 'complainantName', label: 'Complainant Name', type: 'text', required: true, placeholder: 'e.g. Nitin Gupta' },
      { key: 'oppositeParty', label: 'Opposite Party Name (Vendor/Seller)', type: 'text', required: true, placeholder: 'e.g. E-Commerce Retailer Pvt Ltd' },
      { key: 'productService', label: 'Product / Service Name', type: 'text', required: true, placeholder: 'e.g. Premium Smart Phone' },
      { key: 'purchaseDate', label: 'Purchase/Order Date', type: 'date', required: true, placeholder: 'YYYY-MM-DD' },
      { key: 'invoiceNumber', label: 'Invoice / Order Number', type: 'text', required: true, placeholder: 'e.g. INV-2026-9081' },
      { key: 'complaintDetails', label: 'Details of Defect / Grievance', type: 'multiline', required: true, placeholder: 'Describe product defect or service deficiency...' },
      { key: 'compensation', label: 'Compensation Requested (INR)', type: 'number', required: true, placeholder: 'e.g. 50000' },
    ]
  },
  {
    id: 'appealStateCommission',
    title: 'Appeal before State Commission',
    description: 'Appealing District Consumer Commission orders before State Consumer Disputes Redressal Commission.',
    icon: 'trending-up-outline',
    category: 'Consumer',
    estimatedTime: '5 Minutes',
    difficulty: 'Hard',
    rating: 4.8,
    aiReady: true,
    keywords: ['consumer', 'appeal before state commission', 'consumer appeal', 'scdrc appeal'],
  },
  {
    id: 'complaintNationalCommission',
    title: 'Complaint before National Commission',
    description: 'Filing commercial consumer complaints or appeals in NCDRC New Delhi.',
    icon: 'business-outline',
    category: 'Consumer',
    estimatedTime: '6 Minutes',
    difficulty: 'Hard',
    rating: 4.9,
    aiReady: true,
    keywords: ['consumer', 'complaint before national commission', 'ncdrc complaint', 'national consumer forum'],
  },

  // ================= COMPANY (5 templates) =================
  {
    id: 'boardResolution',
    title: 'Board Resolution',
    description: 'Official document recording decisions, authority delegations, or actions approved by directors.',
    icon: 'people-outline',
    category: 'Corporate',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 4.8,
    aiReady: true,
    keywords: ['company', 'board resolution', 'directors resolution', 'board meeting minute'],
  },
  {
    id: 'shareholderResolution',
    title: 'Shareholder Resolution',
    description: 'Resolution passed in Annual General Meetings (AGMs) regarding auditor appointments or changes.',
    icon: 'people-circle-outline',
    category: 'Corporate',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.7,
    aiReady: true,
    keywords: ['company', 'shareholder resolution', 'agm resolution', 'ordinary resolution'],
  },
  {
    id: 'partnershipDissolution',
    title: 'Partnership Dissolution',
    description: 'Deed detailing closure of partnership firms, liability discharges, and asset partitions.',
    icon: 'close-circle-outline',
    category: 'Corporate',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.8,
    aiReady: true,
    keywords: ['company', 'partnership dissolution', 'dissolution deed', 'dissolving partnership firm'],
  },
  {
    id: 'companyNotice',
    title: 'Company Notice',
    description: 'Notice calling for board meetings or shareholder general meetings, listing the agenda.',
    icon: 'notifications-outline',
    category: 'Corporate',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 4.6,
    aiReady: true,
    keywords: ['company', 'company notice', 'meeting notice', 'board meeting circular'],
  },
  {
    id: 'rocApplication',
    title: 'ROC Application',
    description: 'Applications submitted to Registrar of Companies for name approvals or alterations.',
    icon: 'document-text-outline',
    category: 'Corporate',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.7,
    aiReady: true,
    keywords: ['company', 'roc application', 'registrar of companies petition', 'mca application'],
  },

  // ================= MISCELLANEOUS (12 templates) =================
  {
    id: 'rtiApplication',
    title: 'RTI Application',
    description: 'Statutory application seeking government records under Right to Information Act, 2005.',
    icon: 'help-outline',
    category: 'Miscellaneous',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 4.9,
    aiReady: true,
    keywords: ['misc', 'rti application', 'right to information request', 'public info request'],
  },
  {
    id: 'arbitrationPetition',
    title: 'Arbitration Petition',
    description: 'Petition to appoint arbitrators under Section 11 of Arbitration & Conciliation Act.',
    icon: 'people-outline',
    category: 'Miscellaneous',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.8,
    aiReady: true,
    keywords: ['misc', 'arbitration petition', 'section 11 arbitration', 'appoint arbitrator plea'],
  },
  {
    id: 'arbitrationNotice',
    title: 'Arbitration Notice',
    description: 'Notice invoking arbitration clauses and proposing arbitrator names to opponents.',
    icon: 'mail-outline',
    category: 'Miscellaneous',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.8,
    aiReady: true,
    keywords: ['misc', 'arbitration notice', 'invoking arbitration', 'appoint arbitrator notice'],
  },
  {
    id: 'legalOpinion',
    title: 'Legal Opinion',
    description: 'Professional legal advisory advice memo detailing risks, laws, and action paths.',
    icon: 'bulb-outline',
    category: 'Miscellaneous',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.9,
    aiReady: true,
    keywords: ['misc', 'legal opinion', 'counsel advice memo', 'opinion statement'],
  },
  {
    id: 'caseSummary',
    title: 'Case Summary',
    description: 'Overview brief of court cases mapping facts, issues, arguments, and status.',
    icon: 'list-outline',
    category: 'Miscellaneous',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.7,
    aiReady: true,
    keywords: ['misc', 'case summary', 'case brief', 'case overview', 'fact synopsis'],
  },
  {
    id: 'writtenSubmission',
    title: 'Written Submission',
    description: 'Detailed written arguments and legal brief submitted to the bench prior to arguments.',
    icon: 'document-text-outline',
    category: 'Miscellaneous',
    estimatedTime: '4 Minutes',
    difficulty: 'Hard',
    rating: 4.9,
    aiReady: true,
    keywords: ['misc', 'written submission', 'written arguments', 'legal brief', 'trial brief'],
  },
  {
    id: 'synopsis',
    title: 'Synopsis',
    description: 'Summary brief outlining list of dates, facts, and legal questions for the court.',
    icon: 'document-outline',
    category: 'Miscellaneous',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.7,
    aiReady: true,
    keywords: ['misc', 'synopsis', 'case synopsis', 'legal summary points'],
  },
  {
    id: 'chronology',
    title: 'Chronology',
    description: 'Strict list of dates and corresponding facts compiled for court filings.',
    icon: 'time-outline',
    category: 'Miscellaneous',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.8,
    aiReady: true,
    keywords: ['misc', 'chronology', 'list of dates', 'timeline events listing'],
  },
  {
    id: 'vakalatnama',
    title: 'Vakalatnama',
    description: 'Vakalatnama authorization form appointing advocates to represent clients in courts.',
    icon: 'ribbon-outline',
    category: 'Miscellaneous',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 5,
    aiReady: true,
    keywords: ['misc', 'vakalatnama', 'advocate authorization', 'lawyer representation form'],
  },
  {
    id: 'memoOfAppearance',
    title: 'Memo of Appearance',
    description: 'Form filed by advocates to record appearance in court hearings on behalf of client.',
    icon: 'card-outline',
    category: 'Miscellaneous',
    estimatedTime: '2 Minutes',
    difficulty: 'Easy',
    rating: 4.5,
    aiReady: true,
    keywords: ['misc', 'memo of appearance', 'advocate appearance memo', 'hearing memo'],
  },
  {
    id: 'powerOfAttorney',
    title: 'Power of Attorney',
    description: 'Appoint trusted representatives to handle assets and legal matters.',
    icon: 'people-outline',
    category: 'Miscellaneous',
    estimatedTime: '3 Minutes',
    difficulty: 'Medium',
    rating: 4.8,
    aiReady: true,
    keywords: ['misc', 'power of attorney', 'poa', 'agent delegation'],
    fields: [
      { key: 'principalName', label: 'Principal Full Name (Owner)', type: 'text', required: true, placeholder: 'e.g. Devendra Singh' },
      { key: 'attorneyName', label: 'Attorney Full Name (Agent)', type: 'text', required: true, placeholder: 'e.g. Rajendra Singh' },
      { key: 'relationship', label: 'Agent Relationship to Principal', type: 'text', required: true, placeholder: 'e.g. Brother' },
      { key: 'powers', label: 'Powers and Acts Granted', type: 'multiline', required: true, placeholder: 'e.g. To manage bank accounts and sign deeds...' },
      { key: 'effectiveDate', label: 'Effective Date', type: 'date', required: true, placeholder: 'YYYY-MM-DD' },
      { key: 'validity', label: 'Validity Period', type: 'text', required: true, placeholder: 'e.g. Revocable at will' },
      { key: 'revocation', label: 'Revocation Conditions', type: 'text', required: true, placeholder: 'e.g. Revocable by principal return' },
    ]
  },
  {
    id: 'customDraft',
    title: 'Custom Legal Document',
    description: 'Define your own terms to draft custom contracts or petitions.',
    icon: 'create-outline',
    category: 'Miscellaneous',
    estimatedTime: '4 Minutes',
    difficulty: 'Medium',
    rating: 5,
    aiReady: true,
    keywords: ['misc', 'custom draft', 'blank document', 'custom contract', 'general pleading'],
    fields: [
      { key: 'docTitle', label: 'Document Title', type: 'text', required: true, placeholder: 'e.g. Service Agreement' },
      { key: 'parties', label: 'Parties Involved', type: 'text', required: true, placeholder: 'e.g. Client A and Developer B' },
      { key: 'purpose', label: 'Primary Purpose / Objective', type: 'multiline', required: true, placeholder: 'Define what this agreement is about...' },
      { key: 'terms', label: 'Key Terms & Conditions', type: 'multiline', required: true, placeholder: 'List specific rules, payment milestones...' },
    ]
  }
];
