export const INDIAN_STATES_LIST = [
  // 28 States of India
  { name: 'Andhra Pradesh', language: 'Telugu', locale: 'te-IN', flag: '🏛️' },
  { name: 'Arunachal Pradesh', language: 'Hindi', locale: 'hi-IN', flag: '🏔️' },
  { name: 'Assam', language: 'Assamese', locale: 'as-IN', flag: '🦏' },
  { name: 'Bihar', language: 'Hindi', locale: 'hi-IN', flag: '📜' },
  { name: 'Chhattisgarh', language: 'Hindi', locale: 'hi-IN', flag: '🌾' },
  { name: 'Goa', language: 'Konkani', locale: 'gom-IN', flag: '🏖️' },
  { name: 'Gujarat', language: 'Gujarati', locale: 'gu-IN', flag: '🦁' },
  { name: 'Haryana', language: 'Hindi', locale: 'hi-IN', flag: '🌾' },
  { name: 'Himachal Pradesh', language: 'Hindi', locale: 'hi-IN', flag: '🏔️' },
  { name: 'Jharkhand', language: 'Hindi', locale: 'hi-IN', flag: '🌲' },
  { name: 'Karnataka', language: 'Kannada', locale: 'kn-IN', flag: '🏰' },
  { name: 'Kerala', language: 'Malayalam', locale: 'ml-IN', flag: '🌴' },
  { name: 'Madhya Pradesh', language: 'Hindi', locale: 'hi-IN', flag: '🐅' },
  { name: 'Maharashtra', language: 'Marathi', locale: 'mr-IN', flag: '🚩' },
  { name: 'Manipur', language: 'Manipuri', locale: 'mni-IN', flag: '🏞️' },
  { name: 'Meghalaya', language: 'English', locale: 'en-IN', flag: '☁️' },
  { name: 'Mizoram', language: 'English', locale: 'en-IN', flag: '⛰️' },
  { name: 'Nagaland', language: 'English', locale: 'en-IN', flag: '🌄' },
  { name: 'Odisha', language: 'Odia', locale: 'or-IN', flag: '🛕' },
  { name: 'Punjab', language: 'Punjabi', locale: 'pa-IN', flag: '🌾' },
  { name: 'Rajasthan', language: 'Hindi', locale: 'hi-IN', flag: '🏰' },
  { name: 'Sikkim', language: 'Nepali', locale: 'ne-IN', flag: '🏔️' },
  { name: 'Tamil Nadu', language: 'Tamil', locale: 'ta-IN', flag: '🛕' },
  { name: 'Telangana', language: 'Telugu', locale: 'te-IN', flag: '🏛️' },
  { name: 'Tripura', language: 'Bengali', locale: 'bn-IN', flag: '🌿' },
  { name: 'Uttar Pradesh', language: 'Hindi', locale: 'hi-IN', flag: '⚖️' },
  { name: 'Uttarakhand', language: 'Hindi', locale: 'hi-IN', flag: '🏔️' },
  { name: 'West Bengal', language: 'Bengali', locale: 'bn-IN', flag: '🐯' },

  // 8 Union Territories of India
  { name: 'Andaman & Nicobar Islands', language: 'Hindi', locale: 'hi-IN', flag: '🏝️' },
  { name: 'Chandigarh', language: 'Punjabi', locale: 'pa-IN', flag: '🏛️' },
  { name: 'Dadra & Nagar Haveli and Daman & Diu', language: 'Gujarati', locale: 'gu-IN', flag: '🌊' },
  { name: 'Delhi (NCT)', language: 'Hindi', locale: 'hi-IN', flag: '🏛️' },
  { name: 'Jammu & Kashmir', language: 'Urdu', locale: 'ur-IN', flag: '❄️' },
  { name: 'Ladakh', language: 'Urdu', locale: 'ur-IN', flag: '🏔️' },
  { name: 'Lakshadweep', language: 'Malayalam', locale: 'ml-IN', flag: '🏝️' },
  { name: 'Puducherry', language: 'Tamil', locale: 'ta-IN', flag: '🏛️' },
];
