/**
 * AI LEGAL Web - Canonical 91 Legal Templates Registry Data
 * Exporting all 91 templates matching mobile app, categorized by Indian practice areas.
 */

export const CATEGORIES = [
  'All',
  'Civil',
  'Criminal',
  'Corporate',
  'Property',
  'Family',
  'Employment',
  'Banking',
  'Consumer',
  'Contracts',
  'Court Pleadings',
  'Affidavits',
  'Miscellaneous'
];

export const CATEGORY_DEFAULT_FIELDS = {
  'Civil': [
    { key: 'petitionerName', label: 'Petitioner / Plaintiff Name', required: true, placeholder: 'e.g. Amit Sen' },
    { key: 'petitionerAddress', label: 'Petitioner Address', required: true, placeholder: 'e.g. Sector 12, Dwarka, Delhi' },
    { key: 'respondentName', label: 'Respondent / Defendant Name', required: true, placeholder: 'e.g. Vijay Verma' },
    { key: 'respondentAddress', label: 'Respondent Address', required: true, placeholder: 'e.g. Sector 4, Rohini, Delhi' },
    { key: 'courtName', label: 'Court Name', required: true, placeholder: 'e.g. District Court, Saket' },
    { key: 'caseDetails', label: 'Brief Facts of Case', type: 'multiline', required: true, placeholder: 'Explain civil dispute facts...' },
    { key: 'reliefSought', label: 'Relief / Prayer Sought', type: 'multiline', required: true, placeholder: 'Describe what you want court to order...' },
    { key: 'jurisdiction', label: 'Jurisdiction Court Limits', required: true, placeholder: 'e.g. Delhi Courts' },
  ],
  'Criminal': [
    { key: 'complainantName', label: 'Complainant / Petitioner Name', required: true, placeholder: 'e.g. Suresh Prasad' },
    { key: 'complainantAddress', label: 'Complainant Address', required: true, placeholder: 'e.g. B-40, Saket, Delhi' },
    { key: 'accusedName', label: 'Accused Name (if known)', required: false, placeholder: 'e.g. Unknown / Ramesh Rao' },
    { key: 'policeStation', label: 'Local Police Station Name', required: true, placeholder: 'e.g. Saket Police Station' },
    { key: 'incidentDate', label: 'Incident Date', required: true, placeholder: 'YYYY-MM-DD' },
    { key: 'incidentDescription', label: 'Incident Description', type: 'multiline', required: true, placeholder: 'Describe the criminal offence in detail...' },
    { key: 'reliefRequested', label: 'Relief / Action Requested', required: true, placeholder: 'e.g. Arrest of accused and registration of FIR' },
  ],
  'Corporate': [
    { key: 'companyName', label: 'Company / Firm Name', required: true, placeholder: 'e.g. LexCorp Tech Private Limited' },
    { key: 'registeredOffice', label: 'Registered Office Address', required: true, placeholder: 'e.g. Connaught Place, New Delhi' },
    { key: 'meetingDate', label: 'Meeting / Resolution Date', required: true, placeholder: 'YYYY-MM-DD' },
    { key: 'chairpersonName', label: 'Chairperson / Director Name', required: true, placeholder: 'e.g. Devendra Singh' },
    { key: 'agenda', label: 'Agenda of Notice / Resolution', type: 'multiline', required: true, placeholder: 'Explain corporate decisions, share allocations...' },
    { key: 'resolutionDetails', label: 'Resolution / Proposal Details', type: 'multiline', required: true, placeholder: 'Enter resolution details approved...' },
  ],
  'Property': [
    { key: 'transferorName', label: 'Transferor / Seller Name', required: true, placeholder: 'e.g. Rajendra Prasad' },
    { key: 'transfereeName', label: 'Transferee / Buyer Name', required: true, placeholder: 'e.g. Vikram Aditya' },
    { key: 'propertyDescription', label: 'Detailed Property Description', type: 'multiline', required: true, placeholder: 'Plot/Flat details, boundaries, dimensions...' },
    { key: 'considerationAmount', label: 'Sale Value / Consideration (INR)', required: true, placeholder: 'e.g. 5500000' },
    { key: 'keyTerms', label: 'Key Terms / Handover Dates', type: 'multiline', required: true, placeholder: 'Terms of sale, registry timelines...' },
    { key: 'witnessDetails', label: 'Witness Names & Details', required: false, placeholder: 'e.g. Witness A: R.K. Gupta, Witness B: S.K. Roy' },
  ],
  'Family': [
    { key: 'petitionerName', label: 'Petitioner / Spouse Name', required: true, placeholder: 'e.g. Priya Sharma' },
    { key: 'respondentName', label: 'Respondent / Spouse Name', required: true, placeholder: 'e.g. Anil Sharma' },
    { key: 'marriageDate', label: 'Marriage Solemnization Date', required: true, placeholder: 'YYYY-MM-DD' },
    { key: 'marriagePlace', label: 'Place of Marriage', required: true, placeholder: 'e.g. Jaipur, Rajasthan' },
    { key: 'facts', label: 'Crucial Facts / Matrimonial History', type: 'multiline', required: true, placeholder: 'Detail background, separation dates, disputes...' },
    { key: 'reliefRequested', label: 'Relief / Alimony Demanded', type: 'multiline', required: true, placeholder: 'Divorce decree, monthly maintenance of INR 30,000...' },
    { key: 'jurisdiction', label: 'Family Court Jurisdiction', required: true, placeholder: 'e.g. Family Court, Saket, Delhi' },
  ],
  'Employment': [
    { key: 'employerName', label: 'Employer / Company Name', required: true, placeholder: 'e.g. ABC Systems India Pvt Ltd' },
    { key: 'employeeName', label: 'Employee Full Name', required: true, placeholder: 'e.g. Rohan Das' },
    { key: 'jobTitle', label: 'Designation / Job Role', required: true, placeholder: 'e.g. Senior Software Engineer' },
    { key: 'joiningDate', label: 'Date of Joining / Start Date', required: true, placeholder: 'YYYY-MM-DD' },
    { key: 'compensation', label: 'Annual CTC / Salary (INR)', required: true, placeholder: 'e.g. 1200000' },
    { key: 'terminationTerms', label: 'Notice Period / Severance Terms', type: 'multiline', required: true, placeholder: 'e.g. 30 days notice or 1 month salary...' },
  ],
  'Banking': [
    { key: 'borrowerName', label: 'Borrower Name', required: true, placeholder: 'e.g. G.S. Enterprises' },
    { key: 'lenderName', label: 'Lender / Bank Name', required: true, placeholder: 'e.g. State Bank of India' },
    { key: 'loanAmount', label: 'Principal Loan Amount (INR)', required: true, placeholder: 'e.g. 2500000' },
    { key: 'interestRate', label: 'Interest Rate per Annum (%)', required: true, placeholder: 'e.g. 9.5% p.a.' },
    { key: 'repaymentTerms', label: 'Repayment Schedule / Tenure', type: 'multiline', required: true, placeholder: 'e.g. 60 EMIs of INR 52,000...' },
    { key: 'defaultClause', label: 'Default / Collateral Terms', type: 'multiline', required: true, placeholder: 'Consequences of default, mortgaged assets...' },
  ],
  'Consumer': [
    { key: 'complainantName', label: 'Complainant Full Name', required: true, placeholder: 'e.g. Nitin Gupta' },
    { key: 'oppositeParty', label: 'Opposite Party (Vendor/Company)', required: true, placeholder: 'e.g. Prime Gadgets Retail Ltd' },
    { key: 'productService', label: 'Product or Service Details', required: true, placeholder: 'e.g. Premium Smart TV 55 inch' },
    { key: 'purchaseDate', label: 'Purchase/Order Date', required: true, placeholder: 'YYYY-MM-DD' },
    { key: 'grievance', label: 'Grievance / Defect Details', type: 'multiline', required: true, placeholder: 'Explain defect, service deficiency...' },
    { key: 'compensation', label: 'Compensation & Refund Demanded (INR)', required: true, placeholder: 'e.g. 75000' },
  ],
  'Contracts': [
    { key: 'party1', label: 'First Party Name', required: true, placeholder: 'e.g. ABC Solutions' },
    { key: 'party2', label: 'Second Party Name', required: true, placeholder: 'e.g. XYZ Enterprises' },
    { key: 'purpose', label: 'Purpose of Agreement', type: 'multiline', required: true, placeholder: 'Define contract scope and objectives...' },
    { key: 'keyTerms', label: 'Primary Terms & Deliverables', type: 'multiline', required: true, placeholder: 'Milestones, payments, timelines...' },
    { key: 'duration', label: 'Effective Duration', required: true, placeholder: 'e.g. 1 Year from execution date' },
    { key: 'jurisdiction', label: 'Governing Law & Courts', required: true, placeholder: 'e.g. Courts at New Delhi' },
  ],
  'Court Pleadings': [
    { key: 'courtName', label: 'Honorable Court Name', required: true, placeholder: 'e.g. High Court of Delhi' },
    { key: 'caseNumber', label: 'Case Number (if registered)', required: false, placeholder: 'e.g. Arb. P. 104/2026' },
    { key: 'petitioner', label: 'Petitioner / Appellant Name', required: true, placeholder: 'e.g. ABC Enterprises' },
    { key: 'respondent', label: 'Respondent Name', required: true, placeholder: 'e.g. Government of NCT' },
    { key: 'facts', label: 'Grounds & Material Facts', type: 'multiline', required: true, placeholder: 'Detail chronological facts of appeal...' },
    { key: 'prayer', label: 'Prayer / Order Sought', type: 'multiline', required: true, placeholder: 'Plea / Order requested from the Honorable Court...' },
  ],
  'Affidavits': [
    { key: 'deponentName', label: 'Deponent Full Name', required: true, placeholder: 'e.g. Priya Sharma' },
    { key: 'guardianName', label: "Deponent's Father / Spouse Name", required: true, placeholder: 'e.g. Anil Sharma' },
    { key: 'deponentAddress', label: 'Deponent Address', required: true, placeholder: 'e.g. C-15, GK, Delhi' },
    { key: 'purpose', label: 'Purpose of Swearing Affidavit', required: true, placeholder: 'e.g. Verification of identity / Name change' },
    { key: 'declarations', label: 'Declarations (Point by Point)', type: 'multiline', required: true, placeholder: '1. I state that my correct name is Priya...\n2. I state that...' },
    { key: 'verificationPlace', label: 'Verification Place', required: true, placeholder: 'e.g. New Delhi' },
  ],
  'Miscellaneous': [
    { key: 'docTitle', label: 'Document Title', required: true, placeholder: 'e.g. Chronology of Events' },
    { key: 'parties', label: 'Parties Involved', required: true, placeholder: 'e.g. Client A vs Respondent B' },
    { key: 'purpose', label: 'Document Objective', type: 'multiline', required: true, placeholder: 'Background / Context of this compilation...' },
    { key: 'details', label: 'Content Details / Facts', type: 'multiline', required: true, placeholder: 'List out specific points, chronology, opinions...' },
  ]
};

const categoryIconMap = {
  'Civil': '📄',
  'Criminal': '🛡️',
  'Corporate': '🏢',
  'Property': '🏠',
  'Family': '❤️‍🩹',
  'Employment': '💼',
  'Banking': '💰',
  'Consumer': '🛍️',
  'Contracts': '📜',
  'Court Pleadings': '🏛️',
  'Affidavits': '📝',
  'Miscellaneous': '⚖️'
};

export const ALL_91_TEMPLATES = [
  // ================= LEGAL NOTICES (13 templates) =================
  {
    id: 'legalNotice',
    title: 'Legal Notice',
    description: 'Formal legal notices demanding compliance, payments, or actions from an opposing party.',
    icon: '📄',
    category: 'Miscellaneous',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    rating: 5,
    aiReady: true,
    keywords: ['notice', 'legal notice', 'civil notice', 'pre-action notice'],
    fields: [
      { key: 'senderName', label: 'Sender Name', required: true, placeholder: 'e.g. ABC Tech Solutions' },
      { key: 'senderAddress', label: 'Sender Address', required: true, placeholder: 'e.g. 504, Nehru Place, Delhi' },
      { key: 'receiverName', label: 'Receiver Name (Opponent)', required: true, placeholder: 'e.g. XYZ Enterprises' },
      { key: 'receiverAddress', label: 'Receiver Address', required: true, placeholder: 'e.g. Plot 12, Phase 3, Noida' },
      { key: 'subject', label: 'Subject of Legal Notice', required: true, placeholder: 'e.g. Notice for Recovery of Dues' },
      { key: 'facts', label: 'Facts of the Matter', type: 'multiline', required: true, placeholder: 'Explain background, dates, agreements...' },
      { key: 'grounds', label: 'Legal Grounds / Sections', type: 'multiline', required: true, placeholder: 'e.g. Violation of Section 73 of Contract Act...' },
      { key: 'reliefRequested', label: 'Action/Relief Demanded', required: true, placeholder: 'e.g. Pay outstanding amount of INR 5,00,000' },
      { key: 'compliancePeriod', label: 'Compliance Time Limit', required: true, placeholder: '15 Days' },
      { key: 'jurisdiction', label: 'Court Jurisdiction', required: true, placeholder: 'e.g. Courts of Delhi' },
    ]
  },
  {
    id: 'demandNotice',
    title: 'Demand Notice',
    description: 'Notice for payment or performance of an obligation, raising official commercial claims.',
    icon: '💰',
    category: 'Banking',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['notice', 'demand notice', 'outstanding payment', 'remittance demand'],
  },
  {
    id: 'recoveryNotice',
    title: 'Recovery Notice',
    description: 'Legal warning to recover outstanding debts, payments, or loans prior to civil lawsuit.',
    icon: '💰',
    category: 'Banking',
    estimatedTime: '3 Mins',
    difficulty: 'Easy',
    keywords: ['notice', 'recovery notice', 'debt recovery', 'money collection', 'default payment'],
  },
  {
    id: 'showCauseNotice',
    title: 'Show Cause Notice',
    description: 'Official notice demanding explanation for misconduct, defaults, or regulatory breaches.',
    icon: '⚖️',
    category: 'Miscellaneous',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['notice', 'show cause notice', 'scn', 'explanation demand'],
  },
  {
    id: 'evictionNotice',
    title: 'Eviction Notice',
    description: 'Landlord notice demanding tenant vacate premises due to lease expiration or default.',
    icon: '🏠',
    category: 'Property',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['notice', 'eviction notice', 'tenant eviction', 'landlord notice'],
  },
  {
    id: 'breachOfContractNotice',
    title: 'Breach of Contract Notice',
    description: 'Notice served to notify a contracting party of specific contractual violations.',
    icon: '📜',
    category: 'Contracts',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['notice', 'breach of contract notice', 'agreement violation'],
  },
  {
    id: 'defamationNotice',
    title: 'Defamation Notice',
    description: 'Cease and desist warning notice regarding defamatory remarks, statements, or publications.',
    icon: '📄',
    category: 'Civil',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['notice', 'defamation notice', 'slander notice', 'cease and desist'],
  },
  {
    id: 'copyrightNotice',
    title: 'Copyright Notice',
    description: 'Intellectual property notice demanding removal of unauthorized copyrighted materials.',
    icon: '🏢',
    category: 'Corporate',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['notice', 'copyright notice', 'ipr notice', 'dmca notice'],
  },
  {
    id: 'trademarkInfringementNotice',
    title: 'Trademark Infringement Notice',
    description: 'Legal notice demanding cessation of unauthorized brand name or trademark usage.',
    icon: '🏢',
    category: 'Corporate',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['notice', 'trademark infringement notice', 'brand protection'],
  },
  {
    id: 'chequeBounceNotice',
    title: 'Cheque Bounce Notice (Section 138 NI Act)',
    description: 'Statutory legal demand notice for dishonoured cheque claims under Negotiable Instruments Act.',
    icon: '💰',
    category: 'Banking',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['notice', 'cheque bounce notice', 'section 138', '138 ni act', 'dishonoured cheque'],
  },
  {
    id: 'consumerLegalNotice',
    title: 'Consumer Legal Notice',
    description: 'Formal complaint notice served on manufacturers or service providers for deficiency of service.',
    icon: '🛍️',
    category: 'Consumer',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['notice', 'consumer legal notice', 'product defect notice'],
  },
  {
    id: 'employmentTerminationNotice',
    title: 'Employment Termination Notice',
    description: 'Corporate notice served to employees terminating their employment services.',
    icon: '💼',
    category: 'Employment',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['notice', 'employment termination notice', 'relieving notice'],
  },
  {
    id: 'rentDefaultNotice',
    title: 'Rent Default Notice',
    description: 'Formal landlord notice demanding payment of outstanding rental arrears from tenant.',
    icon: '🏠',
    category: 'Property',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['notice', 'rent default notice', 'rental dues notice'],
  },

  // ================= CONTRACTS (15 templates) =================
  {
    id: 'rentAgreement',
    title: 'Rent Agreement',
    description: 'Residential or commercial lease deeds between landlord and tenant.',
    icon: '📜',
    category: 'Contracts',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['agreement', 'rent agreement', 'residential lease', 'tenancy contract'],
    fields: [
      { key: 'landlordName', label: 'Landlord Name', required: true, placeholder: 'e.g. Ramesh Kumar' },
      { key: 'landlordAddress', label: 'Landlord Address', required: true, placeholder: 'e.g. Flat 101, Sector 15, Delhi' },
      { key: 'tenantName', label: 'Tenant Name', required: true, placeholder: 'e.g. Vikram Aditya' },
      { key: 'tenantAddress', label: 'Tenant Address', required: true, placeholder: 'e.g. H-12, Sector 2, Delhi' },
      { key: 'propertyAddress', label: 'Property Address to Lease', required: true, placeholder: 'e.g. Flat 302, Pocket B, Delhi' },
      { key: 'monthlyRent', label: 'Monthly Rent Amount (INR)', required: true, placeholder: 'e.g. 15000' },
      { key: 'securityDeposit', label: 'Security Deposit Amount (INR)', required: true, placeholder: 'e.g. 30000' },
      { key: 'startDate', label: 'Agreement Start Date', required: true, placeholder: 'YYYY-MM-DD' },
      { key: 'duration', label: 'Agreement Duration', required: true, placeholder: '11 Months' },
      { key: 'noticePeriod', label: 'Notice Period required', required: true, placeholder: '1 Month' },
      { key: 'maintenance', label: 'Maintenance Responsibility', required: true, placeholder: 'Tenant' },
      { key: 'jurisdiction', label: 'Governing Jurisdiction / Court', required: true, placeholder: 'e.g. Delhi Courts' },
    ]
  },
  {
    id: 'leaseAgreement',
    title: 'Lease Agreement',
    description: 'Long-term commercial or residential property lease agreements with detailed provisions.',
    icon: '📜',
    category: 'Contracts',
    estimatedTime: '4 Mins',
    difficulty: 'Medium',
    keywords: ['agreement', 'lease agreement', 'commercial lease'],
  },
  {
    id: 'saleAgreement',
    title: 'Sale Agreement',
    description: 'Agreement to sell property detailing payment terms, consideration, and handover schedule.',
    icon: '📜',
    category: 'Contracts',
    estimatedTime: '4 Mins',
    difficulty: 'Medium',
    keywords: ['agreement', 'sale agreement', 'property sale', 'purchase agreement'],
  },
  {
    id: 'employmentAgreement',
    title: 'Employment Agreement',
    description: 'Comprehensive employment terms, employee benefits, code of conduct, and job roles contract.',
    icon: '💼',
    category: 'Employment',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['agreement', 'employment agreement', 'job contract'],
  },
  {
    id: 'serviceAgreement',
    title: 'Service Agreement',
    description: 'Service level agreement (SLA) contract between service provider and corporate client.',
    icon: '📜',
    category: 'Contracts',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['agreement', 'service agreement', 'sla contract'],
  },
  {
    id: 'consultancyAgreement',
    title: 'Consultancy Agreement',
    description: 'Agreement appointing external consultants detailing milestones, fees, and scopes.',
    icon: '📜',
    category: 'Contracts',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['agreement', 'consultancy agreement', 'consultant contract'],
  },
  {
    id: 'vendorAgreement',
    title: 'Vendor Agreement',
    description: 'Supply chain vendor contract detailing product delivery specifications, pricing, and terms.',
    icon: '📜',
    category: 'Contracts',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['agreement', 'vendor agreement', 'supply contract'],
  },
  {
    id: 'partnershipDeed',
    title: 'Partnership Deed',
    description: 'Statutory deed to establish a partnership firm, detailing profit shares and capital ratios.',
    icon: '🏢',
    category: 'Corporate',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['agreement', 'partnership deed', 'firm creation deed'],
  },
  {
    id: 'nda',
    title: 'NDA (Non-Disclosure Agreement)',
    description: 'Mutual or one-way confidentiality agreement restricting sharing of intellectual data.',
    icon: '📜',
    category: 'Contracts',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['agreement', 'nda', 'non-disclosure agreement', 'confidentiality contract'],
  },
  {
    id: 'mou',
    title: 'MoU (Memorandum of Understanding)',
    description: 'Non-binding or semi-binding initial agreement establishing intent of collaboration.',
    icon: '📜',
    category: 'Contracts',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['agreement', 'mou', 'memorandum of understanding'],
  },
  {
    id: 'franchiseAgreement',
    title: 'Franchise Agreement',
    description: 'Agreement for licensing business models, trademarks, and operations to a franchisee.',
    icon: '📜',
    category: 'Contracts',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['agreement', 'franchise agreement', 'brand licensing'],
  },
  {
    id: 'loanAgreement',
    title: 'Loan Agreement',
    description: 'Personal or commercial loan contract detailing interest, default clauses, and EMI schedules.',
    icon: '💰',
    category: 'Banking',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['agreement', 'loan agreement', 'debt contract'],
  },
  {
    id: 'giftDeed',
    title: 'Gift Deed',
    description: 'Legal deed transferring property ownership voluntarily without financial consideration.',
    icon: '🏠',
    category: 'Property',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['agreement', 'gift deed', 'voluntary transfer deed'],
  },
  {
    id: 'mortgageAgreement',
    title: 'Mortgage Agreement',
    description: 'Property mortgaging agreement detailing loan collateral terms, defaults, and foreclosures.',
    icon: '💰',
    category: 'Banking',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['agreement', 'mortgage agreement', 'property mortgage'],
  },
  {
    id: 'powerPurchaseAgreement',
    title: 'Power Purchase Agreement (PPA)',
    description: 'Commercial contract for purchase of energy/power, specifying rates, quotas, and terms.',
    icon: '📜',
    category: 'Contracts',
    estimatedTime: '5 Mins',
    difficulty: 'Hard',
    keywords: ['agreement', 'power purchase agreement', 'ppa'],
  },

  // ================= COURT PLEADINGS (15 templates) =================
  {
    id: 'plaint',
    title: 'Plaint',
    description: 'Primary pleading document filed by the plaintiff to institute a civil suit in court.',
    icon: '🏛️',
    category: 'Court Pleadings',
    estimatedTime: '5 Mins',
    difficulty: 'Hard',
    keywords: ['pleading', 'plaint', 'civil suit filing', 'lawsuit petition'],
  },
  {
    id: 'writtenStatement',
    title: 'Written Statement',
    description: 'Defense reply pleading filed by the defendant in response to the plaint summons.',
    icon: '🏛️',
    category: 'Court Pleadings',
    estimatedTime: '5 Mins',
    difficulty: 'Hard',
    keywords: ['pleading', 'written statement', 'ws', 'defense reply'],
  },
  {
    id: 'counterClaim',
    title: 'Counter Claim',
    description: 'Independent claim raised by the defendant against the plaintiff within the same suit.',
    icon: '🏛️',
    category: 'Court Pleadings',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['pleading', 'counter claim', 'defendant counter lawsuit'],
  },
  {
    id: 'replication',
    title: 'Replication',
    description: 'Pleading response filed by the plaintiff answering the allegations inside the written statement.',
    icon: '🏛️',
    category: 'Court Pleadings',
    estimatedTime: '4 Mins',
    difficulty: 'Medium',
    keywords: ['pleading', 'replication', 'rejoinder'],
  },
  {
    id: 'civilAppeal',
    title: 'Civil Appeal',
    description: 'Appeal petition filed in higher courts against an adverse civil decree or judgment.',
    icon: '🏛️',
    category: 'Court Pleadings',
    estimatedTime: '5 Mins',
    difficulty: 'Hard',
    keywords: ['pleading', 'civil appeal', 'appeal petition'],
  },
  {
    id: 'criminalAppeal',
    title: 'Criminal Appeal',
    description: 'Appeal petition contesting an adverse conviction order in criminal trials.',
    icon: '🏛️',
    category: 'Court Pleadings',
    estimatedTime: '5 Mins',
    difficulty: 'Hard',
    keywords: ['pleading', 'criminal appeal', 'appeal against conviction'],
  },
  {
    id: 'revisionPetition',
    title: 'Revision Petition',
    description: 'Revision plea asking higher courts to examine judicial records for procedural errors.',
    icon: '🏛️',
    category: 'Court Pleadings',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['pleading', 'revision petition', 'civil revision'],
  },
  {
    id: 'reviewPetition',
    title: 'Review Petition',
    description: 'Plea to the court to review its own judgment due to errors apparent on face of record.',
    icon: '🏛️',
    category: 'Court Pleadings',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['pleading', 'review petition', 'judgment review plea'],
  },
  {
    id: 'specialLeavePetition',
    title: 'Special Leave Petition (SLP)',
    description: 'Special petition to approach the Honorable Supreme Court of India under Article 136.',
    icon: '🏛️',
    category: 'Court Pleadings',
    estimatedTime: '6 Mins',
    difficulty: 'Hard',
    keywords: ['pleading', 'slp', 'special leave petition', 'supreme court appeal'],
  },
  {
    id: 'transferPetition',
    title: 'Transfer Petition',
    description: 'Petition to transfer case proceedings from one state court/district to another.',
    icon: '🏛️',
    category: 'Court Pleadings',
    estimatedTime: '4 Mins',
    difficulty: 'Medium',
    keywords: ['pleading', 'transfer petition', 'moving case petition'],
  },
  {
    id: 'caveatPetition',
    title: 'Caveat Petition',
    description: 'Precautionary petition filed to prevent ex-parte orders without notifying the caveator.',
    icon: '🏛️',
    category: 'Court Pleadings',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['pleading', 'caveat petition', 'caveat filing'],
  },
  {
    id: 'executionPetition',
    title: 'Execution Petition',
    description: 'Application to enforce a court decree or judgment against the judgment debtor.',
    icon: '🏛️',
    category: 'Court Pleadings',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['pleading', 'execution petition', 'enforcing decree'],
  },
  {
    id: 'interimApplication',
    title: 'Interim Application',
    description: 'Interlocutory application (IA) seeking temporary directives during suit pendency.',
    icon: '🏛️',
    category: 'Court Pleadings',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['pleading', 'interim application', 'ia filing'],
  },
  {
    id: 'stayApplication',
    title: 'Stay Application',
    description: 'Application seeking stay of execution or temporary injunction orders.',
    icon: '🏛️',
    category: 'Court Pleadings',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['pleading', 'stay application', 'stay of order', 'temporary injunction plea'],
  },
  {
    id: 'delayCondonationApplication',
    title: 'Delay Condonation Application',
    description: 'Application requesting the court to excuse a filing delay under Section 5 Limitation Act.',
    icon: '🏛️',
    category: 'Court Pleadings',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['pleading', 'delay condonation application', 'section 5 limitation'],
  },

  // ================= CRIMINAL (8 templates) =================
  {
    id: 'fir',
    title: 'First Information Report (FIR)',
    description: 'Draft complaints for criminal offenses to be filed at local police stations.',
    icon: '🛡️',
    category: 'Criminal',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['criminal', 'fir', 'first information report', 'police complaint'],
    fields: [
      { key: 'policeStation', label: 'Police Station Name', required: true, placeholder: 'e.g. Saket Police Station' },
      { key: 'complainantName', label: 'Complainant Full Name', required: true, placeholder: 'e.g. Suresh Prasad' },
      { key: 'guardianName', label: "Father's / Husband's Name", required: true, placeholder: 'e.g. Om Prasad' },
      { key: 'complainantAddress', label: 'Contact Address', required: true, placeholder: 'e.g. B-40, Saket, Delhi' },
      { key: 'complainantPhone', label: 'Mobile Number', required: true, placeholder: '10-digit number' },
      { key: 'incidentDate', label: 'Incident Date', required: true, placeholder: 'YYYY-MM-DD' },
      { key: 'incidentTime', label: 'Incident Time', required: true, placeholder: 'e.g. Around 4:30 PM' },
      { key: 'incidentLocation', label: 'Incident Location', required: true, placeholder: 'e.g. Saket Market, Delhi' },
      { key: 'accusedName', label: 'Accused Name (if known)', required: false, placeholder: 'e.g. Unknown' },
      { key: 'incidentDescription', label: 'Description of Incident', type: 'multiline', required: true, placeholder: 'Describe series of events...' },
      { key: 'evidence', label: 'Evidence Available (if any)', required: false, placeholder: 'e.g. CCTV Footage, Phone Logs' },
      { key: 'reliefRequested', label: 'Relief/Action Requested', required: true, placeholder: 'e.g. Request to register FIR' },
    ]
  },
  {
    id: 'criminalComplaint',
    title: 'Criminal Complaint',
    description: 'Private criminal complaint filed directly to Magistrates under Section 200 CrPC.',
    icon: '🛡️',
    category: 'Criminal',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['criminal', 'criminal complaint', 'section 200 crpc'],
  },
  {
    id: 'bailApplication',
    title: 'Bail Application',
    description: 'Regular bail application filed in trials under Section 437/439 of CrPC.',
    icon: '🛡️',
    category: 'Criminal',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['criminal', 'bail application', 'section 439 crpc', 'regular bail'],
  },
  {
    id: 'anticipatoryBail',
    title: 'Anticipatory Bail',
    description: 'Pre-arrest bail application filed under Section 438 of CrPC in anticipation of arrest.',
    icon: '🛡️',
    category: 'Criminal',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['criminal', 'anticipatory bail', 'section 438 crpc'],
  },
  {
    id: 'quashingPetition',
    title: 'Quashing Petition',
    description: 'Petition to quash FIR or proceedings under Section 482 of CrPC in High Courts.',
    icon: '🛡️',
    category: 'Criminal',
    estimatedTime: '5 Mins',
    difficulty: 'Hard',
    keywords: ['criminal', 'quashing petition', 'section 482 crpc'],
  },
  {
    id: 'protestPetition',
    title: 'Protest Petition',
    description: 'Petition challenging closure/final reports submitted by police in criminal investigations.',
    icon: '🛡️',
    category: 'Criminal',
    estimatedTime: '4 Mins',
    difficulty: 'Medium',
    keywords: ['criminal', 'protest petition', 'oppose police report'],
  },
  {
    id: 'dischargeApplication',
    title: 'Discharge Application',
    description: 'Plea to discharge the accused before charges are framed by the trial court.',
    icon: '🛡️',
    category: 'Criminal',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['criminal', 'discharge application', 'discharge plea'],
  },
  {
    id: 'compoundingPetition',
    title: 'Compounding Petition',
    description: 'Application for compounding compoundable offences, finalizing compromises.',
    icon: '🛡️',
    category: 'Criminal',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['criminal', 'compounding petition', 'compromise plea'],
  },

  // ================= AFFIDAVITS (6 templates) =================
  {
    id: 'affidavit',
    title: 'General Affidavit',
    description: 'Sworn oath declarations to prove facts before legal or administrative authorities.',
    icon: '📝',
    category: 'Affidavits',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['affidavit', 'general affidavit', 'sworn declaration'],
    fields: [
      { key: 'deponentName', label: 'Deponent Full Name', required: true, placeholder: 'e.g. Priya Sharma' },
      { key: 'guardianName', label: "Father's / Husband's Name", required: true, placeholder: 'e.g. Anil Sharma' },
      { key: 'deponentAddress', label: 'Residential Address', required: true, placeholder: 'e.g. C-15, GK, Delhi' },
      { key: 'deponentOccupation', label: 'Occupation', required: true, placeholder: 'e.g. Business Executive' },
      { key: 'purpose', label: 'Purpose of Affidavit', required: true, placeholder: 'e.g. Application for Name change' },
      { key: 'declarations', label: 'Declaration Statements (One per point)', type: 'multiline', required: true, placeholder: '1. I state that I have changed my name...' },
      { key: 'verificationPlace', label: 'Place of Verification', required: true, placeholder: 'e.g. New Delhi' },
    ]
  },
  {
    id: 'nameChangeAffidavit',
    title: 'Name Change Affidavit',
    description: 'Sworn affidavit verifying name change for gazette publication and updates.',
    icon: '📝',
    category: 'Affidavits',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['affidavit', 'name change affidavit', 'gazette name change'],
  },
  {
    id: 'addressProofAffidavit',
    title: 'Address Proof Affidavit',
    description: 'Affidavit declaring correct address details in absence of corporate address proof.',
    icon: '📝',
    category: 'Affidavits',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['affidavit', 'address proof affidavit', 'residency declaration'],
  },
  {
    id: 'incomeAffidavit',
    title: 'Income Affidavit',
    description: 'Affidavit confirming annual income metrics for fee concessions or schemes.',
    icon: '📝',
    category: 'Affidavits',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['affidavit', 'income affidavit', 'salary declaration'],
  },
  {
    id: 'marriageAffidavit',
    title: 'Marriage Affidavit',
    description: 'Joint declaration by spouses confirming marriage dates, places, and rituals.',
    icon: '📝',
    category: 'Affidavits',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['affidavit', 'marriage affidavit', 'spouses declaration'],
  },
  {
    id: 'affidavitOfEvidence',
    title: 'Affidavit of Evidence',
    description: 'Sworn affidavit filed as examination-in-chief in civil proceedings.',
    icon: '📝',
    category: 'Affidavits',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['affidavit', 'affidavit of evidence', 'examination in chief'],
  },

  // ================= PROPERTY (8 templates) =================
  {
    id: 'saleDeed',
    title: 'Sale Deed',
    description: 'Final conveyance deed conveying absolute property ownership to the buyer.',
    icon: '🏠',
    category: 'Property',
    estimatedTime: '5 Mins',
    difficulty: 'Hard',
    keywords: ['property', 'sale deed', 'conveyance deed'],
  },
  {
    id: 'giftDeedProperty',
    title: 'Gift Deed (Property)',
    description: 'Property transfer deed by donor to donee without monetary transaction.',
    icon: '🏠',
    category: 'Property',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['property', 'gift deed', 'voluntary transfer deed'],
  },
  {
    id: 'partitionDeed',
    title: 'Partition Deed',
    description: 'Deed dividing joint family property holdings among legal co-owners.',
    icon: '🏠',
    category: 'Property',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['property', 'partition deed', 'property division deed'],
  },
  {
    id: 'relinquishmentDeed',
    title: 'Relinquishment Deed',
    description: 'Deed relinquishing rights in inherited property to other co-heirs.',
    icon: '🏠',
    category: 'Property',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['property', 'relinquishment deed', 'release deed'],
  },
  {
    id: 'will',
    title: 'Will',
    description: 'Last will and testament outlining asset distributions after demise.',
    icon: '🏠',
    category: 'Property',
    estimatedTime: '4 Mins',
    difficulty: 'Medium',
    keywords: ['property', 'will', 'last will and testament'],
  },
  {
    id: 'rectificationDeed',
    title: 'Rectification Deed',
    description: 'Correction deed executed to rectify errors inside registered deeds.',
    icon: '🏠',
    category: 'Property',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['property', 'rectification deed', 'correction deed'],
  },
  {
    id: 'possessionLetter',
    title: 'Possession Letter',
    description: 'Letter issued confirming handover of property possession to buyer.',
    icon: '🏠',
    category: 'Property',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['property', 'possession letter', 'handover letter'],
  },
  {
    id: 'propertyDeclaration',
    title: 'Property Declaration',
    description: 'Self-declaration declaring list of owned assets, lands, and investments.',
    icon: '🏠',
    category: 'Property',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['property', 'property declaration', 'asset declaration'],
  },

  // ================= FAMILY (6 templates) =================
  {
    id: 'divorcePetition',
    title: 'Divorce Petition',
    description: 'Petition filed in Family Courts seeking judicial dissolution of marriage.',
    icon: '❤️‍🩹',
    category: 'Family',
    estimatedTime: '5 Mins',
    difficulty: 'Hard',
    keywords: ['family', 'divorce petition', 'contested divorce'],
  },
  {
    id: 'mutualDivorce',
    title: 'Mutual Consent Divorce Petition',
    description: 'Joint petition seeking mutual consent divorce under Section 13B Hindu Marriage Act.',
    icon: '❤️‍🩹',
    category: 'Family',
    estimatedTime: '4 Mins',
    difficulty: 'Medium',
    keywords: ['family', 'mutual divorce', 'section 13b hma'],
  },
  {
    id: 'childCustodyPetition',
    title: 'Child Custody Petition',
    description: 'Petition seeking guardianship or custody rights of minor child in Family Court.',
    icon: '❤️‍🩹',
    category: 'Family',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['family', 'child custody petition', 'guardian appointment plea'],
  },
  {
    id: 'maintenancePetition',
    title: 'Maintenance Petition',
    description: 'Plea seeking alimony or maintenance under Section 125 of CrPC.',
    icon: '❤️‍🩹',
    category: 'Family',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['family', 'maintenance petition', 'section 125 crpc'],
  },
  {
    id: 'domesticViolenceComplaint',
    title: 'Domestic Violence Complaint',
    description: 'Complaint seeking protection orders under Protection of Women from Domestic Violence Act.',
    icon: '❤️‍🩹',
    category: 'Family',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['family', 'domestic violence complaint', 'dv complaint'],
  },
  {
    id: 'restitutionConjugalRights',
    title: 'Restitution of Conjugal Rights',
    description: 'Petition filed under Section 9 of the Hindu Marriage Act demanding cohabitation resumption.',
    icon: '❤️‍🩹',
    category: 'Family',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['family', 'restitution of conjugal rights', 'section 9 hma'],
  },

  // ================= CONSUMER (3 templates) =================
  {
    id: 'consumerComplaint',
    title: 'Consumer Complaint',
    description: 'Intelligent legal complaints for consumer dispute redressal commissions.',
    icon: '🛍️',
    category: 'Consumer',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['consumer', 'consumer complaint', 'deficiency of service'],
    fields: [
      { key: 'complainantName', label: 'Complainant Name', required: true, placeholder: 'e.g. Nitin Gupta' },
      { key: 'oppositeParty', label: 'Opposite Party Name (Vendor/Seller)', required: true, placeholder: 'e.g. E-Commerce Retailer Pvt Ltd' },
      { key: 'productService', label: 'Product / Service Name', required: true, placeholder: 'e.g. Premium Smart Phone' },
      { key: 'purchaseDate', label: 'Purchase/Order Date', required: true, placeholder: 'YYYY-MM-DD' },
      { key: 'invoiceNumber', label: 'Invoice / Order Number', required: true, placeholder: 'e.g. INV-2026-9081' },
      { key: 'complaintDetails', label: 'Details of Defect / Grievance', type: 'multiline', required: true, placeholder: 'Describe product defect or service deficiency...' },
      { key: 'compensation', label: 'Compensation Requested (INR)', required: true, placeholder: 'e.g. 50000' },
    ]
  },
  {
    id: 'appealStateCommission',
    title: 'Appeal before State Commission',
    description: 'Appealing District Consumer Commission orders before State Consumer Disputes Redressal Commission.',
    icon: '🛍️',
    category: 'Consumer',
    estimatedTime: '5 Mins',
    difficulty: 'Hard',
    keywords: ['consumer', 'appeal before state commission', 'scdrc appeal'],
  },
  {
    id: 'complaintNationalCommission',
    title: 'Complaint before National Commission',
    description: 'Filing commercial consumer complaints or appeals in NCDRC New Delhi.',
    icon: '🛍️',
    category: 'Consumer',
    estimatedTime: '6 Mins',
    difficulty: 'Hard',
    keywords: ['consumer', 'complaint before national commission', 'ncdrc complaint'],
  },

  // ================= COMPANY (5 templates) =================
  {
    id: 'boardResolution',
    title: 'Board Resolution',
    description: 'Official document recording decisions, authority delegations, or actions approved by directors.',
    icon: '🏢',
    category: 'Corporate',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['company', 'board resolution', 'directors resolution'],
  },
  {
    id: 'shareholderResolution',
    title: 'Shareholder Resolution',
    description: 'Resolution passed in Annual General Meetings (AGMs) regarding auditor appointments or changes.',
    icon: '🏢',
    category: 'Corporate',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['company', 'shareholder resolution', 'agm resolution'],
  },
  {
    id: 'partnershipDissolution',
    title: 'Partnership Dissolution',
    description: 'Deed detailing closure of partnership firms, liability discharges, and asset partitions.',
    icon: '🏢',
    category: 'Corporate',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['company', 'partnership dissolution', 'dissolution deed'],
  },
  {
    id: 'companyNotice',
    title: 'Company Notice',
    description: 'Notice calling for board meetings or shareholder general meetings, listing the agenda.',
    icon: '🏢',
    category: 'Corporate',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['company', 'company notice', 'meeting notice'],
  },
  {
    id: 'rocApplication',
    title: 'ROC Application',
    description: 'Applications submitted to Registrar of Companies for name approvals or alterations.',
    icon: '🏢',
    category: 'Corporate',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['company', 'roc application', 'registrar of companies petition'],
  },

  // ================= MISCELLANEOUS (12 templates) =================
  {
    id: 'rtiApplication',
    title: 'RTI Application',
    description: 'Statutory application seeking government records under Right to Information Act, 2005.',
    icon: '⚖️',
    category: 'Miscellaneous',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['misc', 'rti application', 'right to information request'],
  },
  {
    id: 'arbitrationPetition',
    title: 'Arbitration Petition',
    description: 'Petition to appoint arbitrators under Section 11 of Arbitration & Conciliation Act.',
    icon: '⚖️',
    category: 'Miscellaneous',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['misc', 'arbitration petition', 'section 11 arbitration'],
  },
  {
    id: 'arbitrationNotice',
    title: 'Arbitration Notice',
    description: 'Notice invoking arbitration clauses and proposing arbitrator names to opponents.',
    icon: '⚖️',
    category: 'Miscellaneous',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['misc', 'arbitration notice', 'invoking arbitration'],
  },
  {
    id: 'legalOpinion',
    title: 'Legal Opinion',
    description: 'Professional legal advisory advice memo detailing risks, laws, and action paths.',
    icon: '⚖️',
    category: 'Miscellaneous',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['misc', 'legal opinion', 'counsel advice memo'],
  },
  {
    id: 'caseSummary',
    title: 'Case Summary',
    description: 'Overview brief of court cases mapping facts, issues, arguments, and status.',
    icon: '⚖️',
    category: 'Miscellaneous',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['misc', 'case summary', 'case brief'],
  },
  {
    id: 'writtenSubmission',
    title: 'Written Submission',
    description: 'Detailed written arguments and legal brief submitted to the bench prior to arguments.',
    icon: '⚖️',
    category: 'Miscellaneous',
    estimatedTime: '4 Mins',
    difficulty: 'Hard',
    keywords: ['misc', 'written submission', 'written arguments'],
  },
  {
    id: 'synopsis',
    title: 'Synopsis',
    description: 'Summary brief outlining list of dates, facts, and legal questions for the court.',
    icon: '⚖️',
    category: 'Miscellaneous',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['misc', 'synopsis', 'case synopsis'],
  },
  {
    id: 'chronology',
    title: 'Chronology',
    description: 'Strict list of dates and corresponding facts compiled for court filings.',
    icon: '⚖️',
    category: 'Miscellaneous',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['misc', 'chronology', 'list of dates'],
  },
  {
    id: 'vakalatnama',
    title: 'Vakalatnama',
    description: 'Vakalatnama authorization form appointing advocates to represent clients in courts.',
    icon: '⚖️',
    category: 'Miscellaneous',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['misc', 'vakalatnama', 'advocate authorization'],
  },
  {
    id: 'memoOfAppearance',
    title: 'Memo of Appearance',
    description: 'Form filed by advocates to record appearance in court hearings on behalf of client.',
    icon: '⚖️',
    category: 'Miscellaneous',
    estimatedTime: '2 Mins',
    difficulty: 'Easy',
    keywords: ['misc', 'memo of appearance', 'advocate appearance memo'],
  },
  {
    id: 'powerOfAttorney',
    title: 'Power of Attorney',
    description: 'Appoint trusted representatives to handle assets and legal matters.',
    icon: '⚖️',
    category: 'Miscellaneous',
    estimatedTime: '3 Mins',
    difficulty: 'Medium',
    keywords: ['misc', 'power of attorney', 'poa'],
    fields: [
      { key: 'principalName', label: 'Principal Full Name (Owner)', required: true, placeholder: 'e.g. Devendra Singh' },
      { key: 'attorneyName', label: 'Attorney Full Name (Agent)', required: true, placeholder: 'e.g. Rajendra Singh' },
      { key: 'relationship', label: 'Agent Relationship to Principal', required: true, placeholder: 'e.g. Brother' },
      { key: 'powers', label: 'Powers and Acts Granted', type: 'multiline', required: true, placeholder: 'e.g. To manage bank accounts and sign deeds...' },
      { key: 'effectiveDate', label: 'Effective Date', required: true, placeholder: 'YYYY-MM-DD' },
      { key: 'validity', label: 'Validity Period', required: true, placeholder: 'e.g. Revocable at will' },
      { key: 'revocation', label: 'Revocation Conditions', required: true, placeholder: 'e.g. Revocable by principal return' },
    ]
  },
  {
    id: 'customDraft',
    title: 'Custom Legal Document',
    description: 'Define your own terms to draft custom contracts or petitions.',
    icon: '✍️',
    category: 'Miscellaneous',
    estimatedTime: '4 Mins',
    difficulty: 'Medium',
    keywords: ['misc', 'custom draft', 'blank document', 'custom contract'],
    fields: [
      { key: 'docTitle', label: 'Document Title', required: true, placeholder: 'e.g. Service Agreement' },
      { key: 'parties', label: 'Parties Involved', required: true, placeholder: 'e.g. Client A and Developer B' },
      { key: 'purpose', label: 'Primary Purpose / Objective', type: 'multiline', required: true, placeholder: 'Define what this agreement is about...' },
      { key: 'terms', label: 'Key Terms & Conditions', type: 'multiline', required: true, placeholder: 'List specific rules, payment milestones...' },
    ]
  }
];

export function getFieldsForTemplate(template) {
  if (!template) return {};
  if (template.fields && template.fields.length > 0) {
    const fieldsObj = {};
    template.fields.forEach(f => {
      fieldsObj[f.key] = '';
    });
    return fieldsObj;
  }

  const categoryDefaults = CATEGORY_DEFAULT_FIELDS[template.category] || CATEGORY_DEFAULT_FIELDS['Miscellaneous'];
  const fieldsObj = {};
  categoryDefaults.forEach(f => {
    fieldsObj[f.key] = '';
  });
  return fieldsObj;
}
