import React, { useState, useMemo, useEffect } from 'react';
import {
  StyleSheet,
  View,
  Text,
  TextInput,
  Pressable,
  ScrollView,
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  Modal,
  Linking,
  Dimensions,
  BackHandler,
} from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
// @ts-ignore
// eslint-disable-next-line import/no-unresolved
import { Ionicons } from '@expo/vector-icons';
import { useToastContext } from '@/providers';

const FAQ_DATA = [
  {
    category: 'AI Assistant',
    question: 'How do I prompt the Assistant for research?',
    answer: "Use natural legal language. For example, 'Find recent Supreme Court judgments on Section 302 IPC regarding circumstantial evidence' or 'Analyze this paragraph for potential defense arguments'."
  },
  {
    category: 'My Matters',
    question: 'Can I share cases with my junior advocates?',
    answer: "Yes, you can invite team members to collaborate on specific cases, share documents, and exchange notes in real-time."
  },
  {
    category: 'Case Workspace',
    question: 'How do I upload opposition filings to my workspace?',
    answer: "Navigate to the specific Case Workspace page, click 'Upload Document', and choose the PDF or Word files. The system will index them automatically for AI searches."
  },
  {
    category: 'Legal Research',
    question: 'Is the search index updated in real-time?',
    answer: "Yes, our search engine indexes judgements and legal precedents hourly, keeping you updated with the latest High Court and Supreme Court rulings."
  },
  {
    category: 'Draft Maker',
    question: 'Can I export drafts directly to MS Word?',
    answer: "Yes. All drafts and templates generated by Draft Maker can be instantly downloaded as Word documents (.docx) or PDF files with clean legal formatting."
  },
  {
    category: 'Evidence Analyst',
    question: 'What file formats does the Evidence Analyst support?',
    answer: "It supports PDF, DOCX, TXT, and scanned image files (PNG, JPG). For scanned documents, it applies automatic high-accuracy OCR."
  },
  {
    category: 'Account & Login',
    question: 'How do I reset my account password?',
    answer: "Click 'Forgot Password' on the login screen or go to Settings > Security > Change Password to update your credentials safely."
  },
  {
    category: 'Subscription',
    question: 'What features are included in the Pro Plan?',
    answer: "The Pro Plan offers unlimited AI Assistant messages, priority document indexing, advanced notice templates, and multi-device trusted sessions."
  },
  {
    category: 'Billing',
    question: 'Can I get a tax invoice for my subscription?',
    answer: "Yes, GST tax invoices are automatically generated and emailed to your registered address. A dedicated billing hub is coming soon."
  },
  {
    category: 'Troubleshooting',
    question: 'Why is my document upload failing?',
    answer: "Ensure the file size is under 20MB and is not password protected. If the issue persists, clear your browser cache and try again."
  }
];

export default function HelpSupportScreen() {
  const router = useRouter();
  const { showToast } = useToastContext();
  const insets = useSafeAreaInsets();

  // FAQs States
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedFaq, setExpandedFaq] = useState<number | null>(null);

  // Bug Report Form States
  const [bugForm, setBugForm] = useState({
    title: '',
    description: '',
    screenshot: null as string | null,
  });

  // Feature Request Form States
  const [featureForm, setFeatureForm] = useState({
    title: '',
    description: '',
    benefit: '',
  });

  // Feedback Form States
  const [feedbackForm, setFeedbackForm] = useState({
    rating: 0,
    experience: 'Excellent',
    comment: '',
  });
  const [showExperienceModal, setShowExperienceModal] = useState(false);

  // Auto-filled Device info states
  const [deviceInfo, setDeviceInfo] = useState({
    currentScreen: '/settings/help',
    appVersion: '1.2.0',
    osVersion: '',
    deviceModel: '',
  });

  // Detect platform and model on load
  useEffect(() => {
    const os = Platform.OS === 'ios' ? 'iOS' : 'Android';
    const model = Platform.select({
      ios: 'iPhone client',
      android: 'Android handset',
      default: 'Advocate mobile terminal',
    });
    setDeviceInfo((prev) => ({
      ...prev,
      osVersion: `${os} ${Platform.Version}`,
      deviceModel: model,
    }));
  }, []);

  // Android hardware back button fallback to settings index
  useEffect(() => {
    const backHandler = BackHandler.addEventListener('hardwareBackPress', () => {
      if (router.canGoBack()) {
        router.back();
      } else {
        router.replace('/settings');
      }
      return true;
    });
    return () => backHandler.remove();
  }, []);

  // Filter FAQs in real time
  const filteredFaqs = useMemo(() => {
    if (!searchQuery.trim()) return FAQ_DATA;
    const query = searchQuery.toLowerCase();
    return FAQ_DATA.filter(
      (faq) =>
        faq.question.toLowerCase().includes(query) ||
        faq.answer.toLowerCase().includes(query) ||
        faq.category.toLowerCase().includes(query)
    );
  }, [searchQuery]);

  // Support link triggers
  const handleEmailSupport = async () => {
    const url = 'mailto:support@ai-legal.in';
    const canOpen = await Linking.canOpenURL(url);
    if (canOpen) {
      await Linking.openURL(url);
    } else {
      showToast('error', 'Mail Client Error', 'Could not open native email application.');
    }
  };

  const handleWhatsAppSupport = async () => {
    const url = 'https://wa.me/919876543210';
    await Linking.openURL(url);
  };

  // Star Rating clicker
  const handleSelectStar = (ratingVal: number) => {
    setFeedbackForm({ ...feedbackForm, rating: ratingVal });
  };

  // Mock Screenshot attachment trigger
  const handleAttachMockScreenshot = () => {
    setBugForm({ ...bugForm, screenshot: 'screenshot-dossier-err.png' });
    showToast('success', 'File Attached', 'mock-screenshot-dossier-err.png successfully synced.');
  };

  // Form Submissions
  const handleBugSubmit = () => {
    if (!bugForm.title.trim() || !bugForm.description.trim()) {
      showToast('error', 'Validation Failure', 'Please provide a title and detailed description.');
      return;
    }
    showToast('success', 'Report Logged', 'Bug report submitted successfully! Our engineering team will review it. 🐞');
    setBugForm({ title: '', description: '', screenshot: null });
  };

  const handleFeatureSubmit = () => {
    if (!featureForm.title.trim() || !featureForm.description.trim() || !featureForm.benefit.trim()) {
      showToast('error', 'Validation Failure', 'Please complete all feature request fields.');
      return;
    }
    showToast('success', 'Request Sent', 'Feature request submitted! Thank you for helping shape AI LEGAL. 💡');
    setFeatureForm({ title: '', description: '', benefit: '' });
  };

  const handleFeedbackSubmit = () => {
    if (feedbackForm.rating === 0) {
      showToast('error', 'Rating Required', 'Please select a star rating review.');
      return;
    }
    showToast('success', 'Feedback Submitted', 'Thank you for your valuable feedback! We appreciate it. ❤️');
    setFeedbackForm({ rating: 0, experience: 'Excellent', comment: '' });
  };

  const handlePolicyLink = (policy: string) => {
    showToast('info', 'Redirecting', `Opening ${policy} page...`);
  };

  return (
    <View style={styles.container}>
      {/* 1. PROFESSIONAL APP HEADER */}
      <View style={[styles.customHeader, { paddingTop: Math.max(insets.top, 20) + 18, paddingBottom: 18 }]}>
        <View style={styles.headerLeft}>
          <Pressable onPress={() => router.canGoBack() ? router.back() : router.replace('/settings')} style={styles.backBtn}>
            <Ionicons name="chevron-back" size={16} color="#111111" />
            <Text style={styles.backText}>Back</Text>
          </Pressable>
        </View>

        <View style={styles.headerCenter}>
          <Text style={styles.headerTitleText} numberOfLines={1}>Help & Support</Text>
          <Text style={styles.headerSubtitleText} numberOfLines={1}>Advocate Assistance Hub</Text>
        </View>

        <View style={styles.headerRight} />
      </View>

      <SafeAreaView style={{ flex: 1 }} edges={['left', 'right', 'bottom']}>
        <KeyboardAvoidingView
          behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
          style={{ flex: 1 }}
        >
          <ScrollView
            style={styles.body}
            showsVerticalScrollIndicator={false}
            contentContainerStyle={styles.bodyContent}
          >
            {/* Introductory descriptive header card */}
            <View style={[styles.card, styles.introCard]}>
              <View style={styles.introIconWrapper}>
                <Ionicons name="help-buoy-outline" size={24} color="#111111" />
              </View>
              <Text style={styles.introText}>
                Get immediate assistance, browse FAQs, report platform issues, and contact our dedicated support specialists.
              </Text>
            </View>

            {/* SECTION 1: SEARCH FAQ */}
            <View style={styles.card}>
              <Text style={styles.sectionHeading}>Search Guide & FAQ</Text>
              <View style={styles.searchBarWrapper}>
                <Ionicons name="search-outline" size={18} color="#9CA3AF" style={styles.searchIcon} />
                <TextInput
                  style={styles.searchInput}
                  value={searchQuery}
                  onChangeText={setSearchQuery}
                  placeholder="Search FAQs by keyword, category or question..."
                  placeholderTextColor="#9CA3AF"
                />
              </View>

              {/* SECTION 2: FAQ ACCORDIONS */}
              <View style={styles.faqList}>
                {filteredFaqs.length > 0 ? (
                  filteredFaqs.map((faq, idx) => {
                    const isExpanded = expandedFaq === idx;
                    return (
                      <View key={idx} style={styles.faqItem}>
                        <Pressable
                          style={styles.faqHeader}
                          onPress={() => setExpandedFaq(isExpanded ? null : idx)}
                        >
                          <View style={{ flex: 1, paddingRight: 8 }}>
                            <View style={styles.categoryBadge}>
                              <Text style={styles.categoryBadgeText}>{faq.category}</Text>
                            </View>
                            <Text style={styles.faqQuestion}>{faq.question}</Text>
                          </View>
                          <Ionicons
                            name={isExpanded ? 'chevron-up' : 'chevron-down'}
                            size={16}
                            color="#9CA3AF"
                            style={{ alignSelf: 'center' }}
                          />
                        </Pressable>
                        {isExpanded && (
                          <View style={styles.faqAnswerContainer}>
                            <Text style={styles.faqAnswerText}>{faq.answer}</Text>
                          </View>
                        )}
                      </View>
                    );
                  })
                ) : (
                  <View style={styles.emptySearchContainer}>
                    <Text style={styles.emptySearchText}>No FAQ entries match your search query.</Text>
                  </View>
                )}
              </View>
            </View>

            {/* SECTION 3: CONTACT SUPPORT */}
            <View style={styles.card}>
              <Text style={styles.sectionHeading}>Contact Support</Text>
              <Text style={styles.sectionSubtitle}>Get in touch directly with our assist desks.</Text>

              <View style={styles.contactList}>
                {/* Email Support Card */}
                <Pressable style={styles.contactCard} onPress={handleEmailSupport}>
                  <View style={styles.contactIconContainer}>
                    <Ionicons name="mail-outline" size={20} color="#111111" />
                  </View>
                  <View style={{ flex: 1 }}>
                    <View style={styles.contactTitleRow}>
                      <Text style={styles.contactCardTitle}>Email Support</Text>
                      <Ionicons name="arrow-up-forward" size={14} color="#C7D2FE" />
                    </View>
                    <Text style={styles.contactCardVal}>support@ai-legal.in</Text>
                    <Text style={styles.contactResponseTime}>Response: Within 24 Hours</Text>
                  </View>
                </Pressable>

                {/* WhatsApp Support Card */}
                <Pressable style={[styles.contactCard, styles.whatsappBorder]} onPress={handleWhatsAppSupport}>
                  <View style={[styles.contactIconContainer, styles.whatsappBg]}>
                    <Ionicons name="logo-whatsapp" size={20} color="#10B981" />
                  </View>
                  <View style={{ flex: 1 }}>
                    <View style={styles.contactTitleRow}>
                      <Text style={styles.contactCardTitle}>WhatsApp Support</Text>
                      <Ionicons name="arrow-up-forward" size={14} color="#A7F3D0" />
                    </View>
                    <Text style={styles.contactCardVal}>Chat with Support Team</Text>
                    <Text style={styles.contactWhatsAppHours}>Active: 10:00 AM – 7:00 PM</Text>
                  </View>
                </Pressable>

                {/* AI Product Guide Card */}
                <Pressable style={styles.contactCard} onPress={() => router.push('/settings/guide')}>
                  <View style={styles.contactIconContainer}>
                    <Ionicons name="sparkles-outline" size={20} color="#111111" />
                  </View>
                  <View style={{ flex: 1 }}>
                    <View style={styles.contactTitleRow}>
                      <Text style={styles.contactCardTitle}>AI Product Guide</Text>
                      <Ionicons name="chevron-forward" size={14} color="#111111" style={{ alignSelf: 'center', marginLeft: 4 }} />
                    </View>
                    <Text style={styles.contactCardVal}>Interactive workspace assistance</Text>
                    <Text style={styles.contactResponseTime}>Available 24/7 • Step-by-Step guide</Text>
                  </View>
                </Pressable>
              </View>
            </View>

            {/* SECTION 4: SEND FEEDBACK */}
            <View style={styles.card}>
              <Text style={styles.sectionHeading}>Send Feedback</Text>
              <Text style={styles.sectionSubtitle}>Rate your workspace experience quality.</Text>

              <View style={styles.formContainer}>
                {/* Rating stars */}
                <View style={styles.inputGroup}>
                  <Text style={styles.inputLabel}>Rate AI LEGAL™ Platform</Text>
                  <View style={styles.starRow}>
                    {[1, 2, 3, 4, 5].map((star) => (
                      <Pressable key={star} onPress={() => handleSelectStar(star)} style={styles.starPress}>
                        <Ionicons
                          name={star <= feedbackForm.rating ? 'star' : 'star-outline'}
                          size={26}
                          color={star <= feedbackForm.rating ? '#F59E0B' : '#D1D5DB'}
                        />
                      </Pressable>
                    ))}
                  </View>
                </View>

                {/* Quality selector dropdown */}
                <View style={styles.inputGroup}>
                  <Text style={styles.inputLabel}>Experience Quality</Text>
                  <Pressable style={styles.selectTrigger} onPress={() => setShowExperienceModal(true)}>
                    <Text style={styles.selectValueText}>{feedbackForm.experience}</Text>
                    <Ionicons name="chevron-down" size={16} color="#9CA3AF" />
                  </Pressable>
                </View>

                {/* Comments Box */}
                <View style={styles.inputGroup}>
                  <Text style={styles.inputLabel}>Comments / Reviews</Text>
                  <TextInput
                    style={[styles.formInput, styles.formTextArea]}
                    placeholder="Share your thoughts about using AI LEGAL..."
                    placeholderTextColor="#9CA3AF"
                    multiline={true}
                    numberOfLines={3}
                    value={feedbackForm.comment}
                    onChangeText={(v) => setFeedbackForm({ ...feedbackForm, comment: v })}
                  />
                </View>

                <Pressable style={styles.submitBtn} onPress={handleFeedbackSubmit}>
                  <Text style={styles.submitBtnText}>Submit Feedback</Text>
                </Pressable>
              </View>
            </View>

            {/* SECTION 5: REPORT A BUG */}
            <View style={styles.card}>
              <View style={styles.sectionHeaderWithIcon}>
                <Ionicons name="bug-outline" size={18} color="#111111" style={{ marginRight: 6 }} />
                <Text style={styles.sectionHeadingNoMargin}>Report a Bug</Text>
              </View>
              <Text style={styles.sectionSubtitle}>Encountered an issue? Tell our engineering team.</Text>

              <View style={styles.formContainer}>
                <View style={styles.inputGroup}>
                  <Text style={styles.inputLabel}>Bug Title</Text>
                  <TextInput
                    style={styles.formInput}
                    placeholder="e.g. Precedent search fails to index"
                    placeholderTextColor="#9CA3AF"
                    value={bugForm.title}
                    onChangeText={(v) => setBugForm({ ...bugForm, title: v })}
                  />
                </View>

                <View style={styles.inputGroup}>
                  <Text style={styles.inputLabel}>Description</Text>
                  <TextInput
                    style={[styles.formInput, styles.formTextArea]}
                    placeholder="Describe what went wrong and steps to reproduce..."
                    placeholderTextColor="#9CA3AF"
                    multiline={true}
                    numberOfLines={3}
                    value={bugForm.description}
                    onChangeText={(v) => setBugForm({ ...bugForm, description: v })}
                  />
                </View>

                {/* Attach Screenshot upload mock */}
                <View style={styles.inputGroup}>
                  <Text style={styles.inputLabel}>Screenshot Attachment</Text>
                  <Pressable style={styles.fileUploadBtn} onPress={handleAttachMockScreenshot}>
                    <Ionicons name="cloud-upload-outline" size={16} color="#6B7280" style={{ marginRight: 6 }} />
                    <Text style={styles.fileUploadText}>Attach Screenshot (PNG, JPG)</Text>
                  </Pressable>
                  {bugForm.screenshot && (
                    <View style={styles.attachedFileRow}>
                      <Ionicons name="image-outline" size={12} color="#111111" style={{ marginRight: 4 }} />
                      <Text style={styles.attachedFileName} numberOfLines={1}>{bugForm.screenshot}</Text>
                    </View>
                  )}
                </View>

                {/* Auto-filled details */}
                <View style={styles.autoFilledContainer}>
                  <Text style={styles.autoFilledLabel}>SYSTEM DIAGNOSTIC INFO (AUTO-FILLED)</Text>
                  <View style={styles.autoFilledGrid}>
                    <View style={styles.autoFilledItem}>
                      <Text style={styles.diagnosticLabel}>Current Screen</Text>
                      <Text style={styles.diagnosticVal} numberOfLines={1}>{deviceInfo.currentScreen}</Text>
                    </View>
                    <View style={styles.autoFilledItem}>
                      <Text style={styles.diagnosticLabel}>Detected OS</Text>
                      <Text style={styles.diagnosticVal} numberOfLines={1}>{deviceInfo.osVersion}</Text>
                    </View>
                    <View style={styles.autoFilledItem}>
                      <Text style={styles.diagnosticLabel}>Device Model</Text>
                      <Text style={styles.diagnosticVal} numberOfLines={1}>{deviceInfo.deviceModel}</Text>
                    </View>
                    <View style={styles.autoFilledItem}>
                      <Text style={styles.diagnosticLabel}>App Version</Text>
                      <Text style={styles.diagnosticVal} numberOfLines={1}>{deviceInfo.appVersion}</Text>
                    </View>
                  </View>
                </View>

                <Pressable style={styles.submitBtn} onPress={handleBugSubmit}>
                  <Text style={styles.submitBtnText}>Submit Bug Report</Text>
                </Pressable>
              </View>
            </View>

            {/* SECTION 6: REQUEST FEATURE */}
            <View style={styles.card}>
              <View style={styles.sectionHeaderWithIcon}>
                <Ionicons name="sparkles-outline" size={18} color="#111111" style={{ marginRight: 6 }} />
                <Text style={styles.sectionHeadingNoMargin}>Request Feature</Text>
              </View>
              <Text style={styles.sectionSubtitle}>Suggest product ideas to shape legal automation.</Text>

              <View style={styles.formContainer}>
                <View style={styles.inputGroup}>
                  <Text style={styles.inputLabel}>Feature Title</Text>
                  <TextInput
                    style={styles.formInput}
                    placeholder="e.g. Integrations with district court diaries"
                    placeholderTextColor="#9CA3AF"
                    value={featureForm.title}
                    onChangeText={(v) => setFeatureForm({ ...featureForm, title: v })}
                  />
                </View>

                <View style={styles.inputGroup}>
                  <Text style={styles.inputLabel}>Description</Text>
                  <TextInput
                    style={[styles.formInput, styles.formTextArea]}
                    placeholder="Describe the feature request in detail..."
                    placeholderTextColor="#9CA3AF"
                    multiline={true}
                    numberOfLines={3}
                    value={featureForm.description}
                    onChangeText={(v) => setFeatureForm({ ...featureForm, description: v })}
                  />
                </View>

                <View style={styles.inputGroup}>
                  <Text style={styles.inputLabel}>Expected Benefit</Text>
                  <TextInput
                    style={[styles.formInput, styles.formTextArea]}
                    placeholder="Explain how this suggestion benefits active advocate litigation..."
                    placeholderTextColor="#9CA3AF"
                    multiline={true}
                    numberOfLines={2}
                    value={featureForm.benefit}
                    onChangeText={(v) => setFeatureForm({ ...featureForm, benefit: v })}
                  />
                </View>

                <Pressable style={styles.submitBtn} onPress={handleFeatureSubmit}>
                  <Text style={styles.submitBtnText}>Submit Request</Text>
                </Pressable>
              </View>
            </View>

            {/* SECTION 7: LEGAL INFORMATION FOOTER */}
            <View style={styles.footer}>
              <Text style={styles.footerLabel}>Legal & Privacy Policies</Text>
              <View style={styles.footerLinksRow}>
                <Pressable onPress={() => handlePolicyLink('Privacy Policy')}>
                  <Text style={styles.footerLinkText}>Privacy Policy</Text>
                </Pressable>
                <Text style={styles.footerLinkDivider}>•</Text>
                <Pressable onPress={() => handlePolicyLink('Terms & Conditions')}>
                  <Text style={styles.footerLinkText}>Terms & Conditions</Text>
                </Pressable>
                <Text style={styles.footerLinkDivider}>•</Text>
                <Pressable onPress={() => handlePolicyLink('Cookie Policy')}>
                  <Text style={styles.footerLinkText}>Cookie Policy</Text>
                </Pressable>
              </View>

              <View style={styles.copyrightSection}>
                <Text style={styles.footerCopyrightTitle}>AI LEGAL™</Text>
                <Text style={styles.footerCopyrightDesc}>Advocate Edition • Version {deviceInfo.appVersion}</Text>
                <Text style={styles.footerCopyrightText}>© 2026 AI LEGAL™. All Rights Reserved.</Text>
              </View>
            </View>

            {/* Inset safe spacing */}
            <View style={{ height: 40 }} />
          </ScrollView>
        </KeyboardAvoidingView>
      </SafeAreaView>

      {/* Selector modal for experience rating */}
      <Modal
        visible={showExperienceModal}
        transparent={true}
        animationType="fade"
        onRequestClose={() => setShowExperienceModal(false)}
      >
        <View style={styles.modalBackdrop}>
          <Pressable style={styles.modalDismissBg} onPress={() => setShowExperienceModal(false)} />
          <View style={styles.modalContent}>
            <View style={styles.modalHeader}>
              <Text style={styles.modalTitle}>Experience Quality</Text>
              <Pressable onPress={() => setShowExperienceModal(false)}>
                <Ionicons name="close" size={22} color="#4B5563" />
              </Pressable>
            </View>
            <View style={{ paddingBottom: 24 }}>
              {['Excellent', 'Good', 'Average', 'Below Average'].map((val) => {
                const isSelected = feedbackForm.experience === val;
                return (
                  <Pressable
                    key={val}
                    style={[styles.pickerOptRow, isSelected && styles.pickerOptRowSelected]}
                    onPress={() => {
                      setFeedbackForm({ ...feedbackForm, experience: val });
                      setShowExperienceModal(false);
                    }}
                  >
                    <Text style={[styles.pickerOptText, isSelected && styles.pickerOptTextSelected]}>
                      {val}
                    </Text>
                    {isSelected ? <Ionicons name="checkmark" size={18} color="#111111" /> : null}
                  </Pressable>
                );
              })}
            </View>
          </View>
        </View>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  customHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#ECECEC',
    backgroundColor: '#FFFFFF',
  },
  headerLeft: {
    flex: 1.2,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  headerCenter: {
    flex: 2.2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerRight: {
    flex: 1.3,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F5F5F5',
    backgroundColor: '#F9FAFB',
  },
  backText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#111111',
    marginLeft: 2,
  },
  headerTitleText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1F2937',
    textAlign: 'center',
  },
  headerSubtitleText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#9CA3AF',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: 2,
    textAlign: 'center',
  },
  body: {
    flex: 1,
  },
  bodyContent: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 24,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ECECEC',
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 3,
  },
  introCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#F5F5F5',
    borderColor: '#E0DEFF',
  },
  introIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  introText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    color: '#374151',
    lineHeight: 18,
  },
  sectionHeading: {
    fontSize: 11,
    fontWeight: '800',
    color: '#111111',
    textTransform: 'uppercase',
    letterSpacing: 1,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    paddingBottom: 8,
    marginBottom: 12,
  },
  sectionHeadingNoMargin: {
    fontSize: 11,
    fontWeight: '800',
    color: '#111111',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  sectionSubtitle: {
    fontSize: 11.5,
    color: '#6B7280',
    fontWeight: '500',
    marginBottom: 16,
  },
  searchBarWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#ECECEC',
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 42,
    marginBottom: 16,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: '#1F2937',
    fontWeight: '600',
    paddingVertical: 4,
  },
  faqList: {
    gap: 12,
  },
  faqItem: {
    borderWidth: 1,
    borderColor: '#F3F4F6',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  faqHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 14,
  },
  categoryBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 4,
    marginBottom: 6,
  },
  categoryBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#4F8CFF',
    textTransform: 'uppercase',
  },
  faqQuestion: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#374151',
  },
  faqAnswerContainer: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    borderTopWidth: 1,
    borderTopColor: '#F9FAFB',
    paddingTop: 8,
  },
  faqAnswerText: {
    fontSize: 12,
    color: '#6B7280',
    lineHeight: 18,
    fontWeight: '500',
  },
  emptySearchContainer: {
    paddingVertical: 20,
    alignItems: 'center',
  },
  emptySearchText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
    fontStyle: 'italic',
  },
  contactList: {
    gap: 12,
  },
  contactCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 14,
    borderWidth: 1,
    borderColor: '#ECECEC',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    gap: 12,
  },
  contactIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  contactTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 6,
  },
  contactCardTitle: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#374151',
  },
  contactCardVal: {
    fontSize: 11,
    fontWeight: '600',
    color: '#6B7280',
    marginTop: 2,
  },
  contactResponseTime: {
    fontSize: 10,
    fontWeight: '800',
    color: '#111111',
    marginTop: 6,
    textTransform: 'uppercase',
  },
  whatsappBorder: {
    borderColor: '#A7F3D0',
  },
  whatsappBg: {
    backgroundColor: '#ECFDF5',
  },
  contactWhatsAppHours: {
    fontSize: 10,
    fontWeight: '800',
    color: '#10B981',
    marginTop: 6,
    textTransform: 'uppercase',
  },
  disabledContactCard: {
    opacity: 0.65,
    backgroundColor: '#F9FAFB',
  },
  disabledIconBg: {
    backgroundColor: '#E5E7EB',
  },
  disabledCardTitle: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#9CA3AF',
  },
  comingSoonBadge: {
    backgroundColor: '#E0F2FE',
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
  },
  comingSoonText: {
    fontSize: 8,
    fontWeight: '800',
    color: '#0284C7',
  },
  formContainer: {
    gap: 12,
  },
  inputGroup: {
    gap: 5,
  },
  inputLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#9CA3AF',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  starRow: {
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 4,
  },
  starPress: {
    padding: 2,
  },
  selectTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#ECECEC',
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 38,
    backgroundColor: '#FFFFFF',
  },
  selectValueText: {
    fontSize: 13,
    color: '#1F2937',
    fontWeight: '600',
  },
  formInput: {
    borderWidth: 1,
    borderColor: '#ECECEC',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 13,
    color: '#1F2937',
    backgroundColor: '#FFFFFF',
  },
  formTextArea: {
    textAlignVertical: 'top',
    minHeight: 80,
  },
  submitBtn: {
    backgroundColor: '#111111',
    borderRadius: 10,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#111111',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
    marginTop: 8,
  },
  submitBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  sectionHeaderWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    paddingBottom: 8,
    marginBottom: 10,
  },
  fileUploadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#ECECEC',
    borderStyle: 'dashed',
    borderRadius: 10,
    height: 38,
    backgroundColor: '#F9FAFB',
  },
  fileUploadText: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '600',
  },
  attachedFileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  attachedFileName: {
    fontSize: 11,
    color: '#111111',
    fontWeight: '700',
  },
  autoFilledContainer: {
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    padding: 12,
    marginTop: 4,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  autoFilledLabel: {
    fontSize: 8.5,
    fontWeight: '800',
    color: '#9CA3AF',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  autoFilledGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 8,
  },
  autoFilledItem: {
    width: '50%',
    paddingRight: 6,
  },
  diagnosticLabel: {
    fontSize: 8,
    fontWeight: '700',
    color: '#9CA3AF',
    textTransform: 'uppercase',
  },
  diagnosticVal: {
    fontSize: 11,
    color: '#4B5563',
    fontWeight: '600',
    marginTop: 1,
  },
  footer: {
    marginTop: 16,
    paddingVertical: 24,
    borderTopWidth: 1,
    borderTopColor: '#ECECEC',
    alignItems: 'center',
  },
  footerLabel: {
    fontSize: 9,
    fontWeight: '800',
    color: '#111111',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  footerLinksRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 20,
  },
  footerLinkText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#111111',
    textDecorationLine: 'underline',
  },
  footerLinkDivider: {
    fontSize: 12,
    color: '#D1D5DB',
  },
  copyrightSection: {
    alignItems: 'center',
    gap: 2,
  },
  footerCopyrightTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#374151',
  },
  footerCopyrightDesc: {
    fontSize: 10,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  footerCopyrightText: {
    fontSize: 9.5,
    fontWeight: '600',
    color: '#9CA3AF',
    marginTop: 2,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(31, 41, 55, 0.6)',
    justifyContent: 'flex-end',
  },
  modalDismissBg: {
    flex: 1,
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#ECECEC',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1F2937',
  },
  pickerOptRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F9FAFB',
  },
  pickerOptRowSelected: {
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  pickerOptText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
  },
  pickerOptTextSelected: {
    color: '#111111',
    fontWeight: '800',
  },
});
