import React, { useState, useEffect, useMemo } from 'react';
import { Link } from 'react-router-dom';
import { 
  Search, Mail, Phone, MessageSquare, ChevronDown, ChevronUp, 
  Star, Bug, Sparkles, FileText, ArrowUpRight, Scale, MessageCircle
} from 'lucide-react';
import toast from 'react-hot-toast';
import axios from 'axios';
import { apis } from '../types';

const FAQ_DATA = [
  {
    category: 'AI Legal Assistant',
    question: 'How do I prompt the Assistant for research?',
    answer: "Use natural legal language. For example, 'Find recent Supreme Court judgments on Section 302 IPC regarding circumstantial evidence' or 'Analyze this paragraph for potential defense arguments'."
  },
  {
    category: 'My Matters',
    question: 'Can I share cases with my junior advocates?',
    answer: "Yes, you can invite team members to collaborate on specific cases, share documents, and exchange notes in real-time."
  },
  {
    category: 'Case Workspace',
    question: 'How do I upload opposition filings to my workspace?',
    answer: "Navigate to the specific Case Workspace page, click 'Upload Document', and choose the PDF or Word files. The system will index them automatically for AI searches."
  },
  {
    category: 'Legal Research',
    question: 'Is the search index updated in real-time?',
    answer: "Yes, our search engine indexes judgements and legal precedents hourly, keeping you updated with the latest High Court and Supreme Court rulings."
  },
  {
    category: 'Draft Maker',
    question: 'Can I export drafts directly to MS Word?',
    answer: "Yes. All drafts and templates generated by Draft Maker can be instantly downloaded as Word documents (.docx) or PDF files with clean legal formatting."
  },
  {
    category: 'Evidence Analyst',
    question: 'What file formats does the Evidence Analyst support?',
    answer: "It supports PDF, DOCX, TXT, and scanned image files (PNG, JPG). For scanned documents, it applies automatic high-accuracy OCR."
  },
  {
    category: 'Account & Login',
    question: 'How do I reset my account password?',
    answer: "Click 'Forgot Password' on the login screen or go to Settings > Security > Change Password to update your credentials safely."
  },
  {
    category: 'Subscription',
    question: 'What features are included in the Pro Plan?',
    answer: "The Pro Plan offers unlimited AI Assistant messages, priority document indexing, advanced notice templates, and multi-device trusted sessions."
  },
  {
    category: 'Billing (future)',
    question: 'Can I get a tax invoice for my subscription?',
    answer: "Yes, GST tax invoices are automatically generated and emailed to your registered address. A dedicated billing hub is coming soon."
  },
  {
    category: 'Troubleshooting',
    question: 'Why is my document upload failing?',
    answer: "Ensure the file size is under 20MB and is not password protected. If the issue persists, clear your browser cache and try again."
  }
];

const HelpSupport = () => {
  // FAQs States
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedFaq, setExpandedFaq] = useState(null);

  // Bug Report Form States
  const [bugForm, setBugForm] = useState({
    title: '',
    description: '',
    screenshot: null
  });
  const [currentPage, setCurrentPage] = useState('');
  const [browserInfo, setBrowserInfo] = useState('');

  // Feature Request Form States
  const [featureForm, setFeatureForm] = useState({
    title: '',
    description: '',
    benefit: ''
  });

  // Feedback Form States
  const [feedbackForm, setFeedbackForm] = useState({
    rating: 0,
    experience: 'Excellent',
    comment: ''
  });
  const [hoverRating, setHoverRating] = useState(0);

  // Auto-fill page and browser info
  useEffect(() => {
    setCurrentPage(window.location.href);
    
    const userAgent = navigator.userAgent;
    let browser = 'Unknown Browser';
    let os = 'Unknown OS';

    if (userAgent.indexOf('Firefox') > -1) browser = 'Mozilla Firefox';
    else if (userAgent.indexOf('Chrome') > -1) browser = 'Google Chrome';
    else if (userAgent.indexOf('Safari') > -1) browser = 'Apple Safari';
    else if (userAgent.indexOf('Edge') > -1) browser = 'Microsoft Edge';

    if (userAgent.indexOf('Windows') > -1) os = 'Windows';
    else if (userAgent.indexOf('Mac') > -1) os = 'macOS';
    else if (userAgent.indexOf('Linux') > -1) os = 'Linux';
    else if (userAgent.indexOf('Android') > -1) os = 'Android';
    else if (userAgent.indexOf('iPhone') > -1) os = 'iOS';

    setBrowserInfo(`${browser} on ${os}`);
  }, []);

  // Filter FAQs based on search query
  const filteredFaqs = useMemo(() => {
    if (!searchQuery.trim()) return FAQ_DATA;
    return FAQ_DATA.filter(
      faq => 
        faq.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
        faq.answer.toLowerCase().includes(searchQuery.toLowerCase()) ||
        faq.category.toLowerCase().includes(searchQuery.toLowerCase())
    );
  }, [searchQuery]);

  // Form Submissions
  const handleBugSubmit = async (e) => {
    e.preventDefault();
    if (!bugForm.title.trim() || !bugForm.description.trim()) {
      toast.error('Please fill in the bug title and description.');
      return;
    }

    const user = JSON.parse(localStorage.getItem('user') || '{}');
    const payload = {
      name: user.name || 'Enterprise Advocate',
      email: user.email || 'advocate@ai-legal.in',
      userId: user._id || null,
      issueType: 'Bug Report',
      title: bugForm.title,
      message: bugForm.description,
      category: currentPage || 'Support Center',
      priority: 'Medium',
      device: browserInfo || 'Web Browser',
      appVersion: 'v1.2.0 (Build 402)',
      status: 'pending'
    };

    try {
      const headers = user.token ? { Authorization: `Bearer ${user.token}` } : {};
      await axios.post(apis.support, payload, { headers });
      toast.success('Bug report submitted successfully! Our engineering team will look into it. 🐞');
      setBugForm({ title: '', description: '', screenshot: null });
    } catch (err) {
      console.error(err);
      toast.error('Failed to submit bug report. Please try again.');
    }
  };

  const handleFeatureSubmit = async (e) => {
    e.preventDefault();
    if (!featureForm.title.trim() || !featureForm.description.trim() || !featureForm.benefit.trim()) {
      toast.error('Please fill in all feature request fields.');
      return;
    }

    const user = JSON.parse(localStorage.getItem('user') || '{}');
    const payload = {
      name: user.name || 'Enterprise Advocate',
      email: user.email || 'advocate@ai-legal.in',
      userId: user._id || null,
      issueType: 'Feature Request',
      title: featureForm.title,
      message: featureForm.description,
      whyNeeded: featureForm.benefit,
      category: 'General',
      priority: 'Normal',
      status: 'Review'
    };

    try {
      const headers = user.token ? { Authorization: `Bearer ${user.token}` } : {};
      await axios.post(apis.support, payload, { headers });
      toast.success('Feature request submitted! Thank you for helping shape AI Legal™. 💡');
      setFeatureForm({ title: '', description: '', benefit: '' });
    } catch (err) {
      console.error(err);
      toast.error('Failed to submit feature request. Please try again.');
    }
  };

  const handleFeedbackSubmit = (e) => {
    e.preventDefault();
    if (feedbackForm.rating === 0) {
      toast.error('Please select a star rating.');
      return;
    }
    toast.success('Thank you for your valuable feedback! We appreciate it. ❤️');
    setFeedbackForm({ rating: 0, experience: 'Excellent', comment: '' });
  };

  const handleFileChange = (e) => {
    if (e.target.files && e.target.files[0]) {
      setBugForm({ ...bugForm, screenshot: e.target.files[0] });
      toast.success('Screenshot attached successfully!');
    }
  };

  return (
    <div className="min-h-full bg-white flex flex-col font-sans select-text p-6 lg:p-8 space-y-12 max-w-6xl mx-auto">
      
      {/* Header */}
      <div className="border-b border-slate-100 pb-6">
        <div className="flex items-center gap-3 text-[#6D5DFC] mb-2">
          <Scale className="w-8 h-8" />
          <h1 className="text-2xl font-black text-slate-800 tracking-tight">AI Legal™ Support Center</h1>
        </div>
        <p className="text-xs font-semibold text-slate-400 mt-1">Get immediate assistance, search FAQs, report issues, and share feedback.</p>
      </div>

      {/* 1. Help Center & FAQs */}
      <section className="space-y-6">
        <div>
          <h2 className="text-sm font-black uppercase tracking-widest text-[#6D5DFC] mb-1">Help Center & FAQs</h2>
          <p className="text-xs font-semibold text-slate-400">Searchable guide for common platform queries.</p>
        </div>

        {/* Search Input */}
        <div className="relative max-w-lg">
          <Search className="absolute left-3.5 top-3 w-4 h-4 text-slate-400" />
          <input
            type="text"
            placeholder="Search FAQs by keywords, categories, or questions..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 border border-slate-200 rounded-xl text-xs font-bold bg-[#F9FAFB] focus:bg-white focus:outline-none focus:border-[#6D5DFC] focus:ring-1 focus:ring-[#6D5DFC] transition-all placeholder-slate-400"
          />
        </div>

        {/* FAQs List */}
        <div className="border border-slate-100 rounded-2xl overflow-hidden divide-y divide-slate-100">
          {filteredFaqs.length > 0 ? (
            filteredFaqs.map((faq, index) => {
              const isExpanded = expandedFaq === index;
              return (
                <div key={index} className="bg-white hover:bg-slate-50/30 transition-colors">
                  <button
                    onClick={() => setExpandedFaq(isExpanded ? null : index)}
                    className="w-full py-4 px-6 flex items-center justify-between text-left focus:outline-none"
                  >
                    <div className="space-y-1">
                      <span className="inline-block text-[9px] font-black uppercase tracking-widest text-[#4F8CFF] bg-[#4F8CFF]/10 px-2 py-0.5 rounded">
                        {faq.category}
                      </span>
                      <h3 className="text-xs font-bold text-slate-700">{faq.question}</h3>
                    </div>
                    {isExpanded ? (
                      <ChevronUp className="w-4 h-4 text-slate-400 shrink-0 ml-4" />
                    ) : (
                      <ChevronDown className="w-4 h-4 text-slate-400 shrink-0 ml-4" />
                    )}
                  </button>
                  {isExpanded && (
                    <div className="px-6 pb-5 pt-1 text-xs font-medium text-slate-500 leading-relaxed border-t border-slate-50/50">
                      {faq.answer}
                    </div>
                  )}
                </div>
              );
            })
          ) : (
            <div className="p-8 text-center text-xs font-bold text-slate-400">
              No FAQs matched your search terms. Please try another query.
            </div>
          )}
        </div>
      </section>

      {/* Grid for Contact & Feedback */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        
        {/* 2. Contact Support */}
        <section className="space-y-6">
          <div>
            <h2 className="text-sm font-black uppercase tracking-widest text-[#6D5DFC] mb-1">Contact Support</h2>
            <p className="text-xs font-semibold text-slate-400">Get in touch directly with our support desk.</p>
          </div>

          <div className="grid grid-cols-1 gap-4">
            
            {/* Email card */}
            <a 
              href="mailto:support@ai-legal.in" 
              className="p-5 border border-slate-100 rounded-2xl bg-white hover:border-[#6D5DFC]/30 hover:bg-[#F9FAFB]/20 transition-all flex items-start gap-4 text-left group"
            >
              <div className="w-10 h-10 rounded-xl bg-[#6D5DFC]/10 flex items-center justify-center text-[#6D5DFC] shrink-0">
                <Mail className="w-5 h-5" />
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <h3 className="text-xs font-bold text-slate-800">Email Support</h3>
                  <ArrowUpRight className="w-3.5 h-3.5 text-slate-300 group-hover:text-[#6D5DFC] transition-colors" />
                </div>
                <p className="text-[10px] text-slate-400 font-semibold mt-0.5">support@ai-legal.in</p>
                <p className="text-[10px] font-bold text-slate-500 mt-2">Response: Within 24 Hours</p>
              </div>
            </a>

            {/* WhatsApp Support */}
            <a 
              href="https://wa.me/919876543210" 
              target="_blank" 
              rel="noopener noreferrer" 
              className="p-5 border border-slate-100 rounded-2xl bg-white hover:border-[#6D5DFC]/30 hover:bg-[#F9FAFB]/20 transition-all flex items-start gap-4 text-left group"
            >
              <div className="w-10 h-10 rounded-xl bg-emerald-50 flex items-center justify-center text-emerald-500 shrink-0">
                <MessageCircle className="w-5 h-5" />
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <h3 className="text-xs font-bold text-slate-800">WhatsApp Support</h3>
                  <ArrowUpRight className="w-3.5 h-3.5 text-slate-300 group-hover:text-emerald-500 transition-colors" />
                </div>
                <p className="text-[10px] text-slate-400 font-semibold mt-0.5">Instant chat support with advocates support specialists.</p>
                <p className="text-[10px] font-bold text-emerald-500 mt-2">Active: 10:00 AM - 7:00 PM</p>
              </div>
            </a>

            {/* Live Chat card */}
            <div className="p-5 border border-slate-100 rounded-2xl bg-[#F9FAFB]/50 flex items-start gap-4 text-left opacity-75">
              <div className="w-10 h-10 rounded-xl bg-slate-100 flex items-center justify-center text-slate-400 shrink-0">
                <MessageSquare className="w-5 h-5" />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <h3 className="text-xs font-bold text-slate-400">Live Chat</h3>
                  <span className="text-[9px] font-black uppercase tracking-widest text-[#4F8CFF] bg-[#4F8CFF]/10 px-1.5 py-0.5 rounded">Coming Soon</span>
                </div>
                <p className="text-[10px] text-slate-400 font-semibold mt-0.5">Direct interactive session helper within workspace.</p>
              </div>
            </div>

          </div>
        </section>

        {/* 5. Send Feedback */}
        <section className="space-y-6">
          <div>
            <h2 className="text-sm font-black uppercase tracking-widest text-[#6D5DFC] mb-1">Send Feedback</h2>
            <p className="text-xs font-semibold text-slate-400">Rate your experience and help us improve.</p>
          </div>

          <form onSubmit={handleFeedbackSubmit} className="p-6 border border-slate-100 rounded-2xl space-y-4 bg-white">
            {/* Stars Rating */}
            <div>
              <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest block mb-2">Rate AI LEGAL</label>
              <div className="flex items-center gap-1.5">
                {[1, 2, 3, 4, 5].map((star) => (
                  <button
                    key={star}
                    type="button"
                    onClick={() => setFeedbackForm({ ...feedbackForm, rating: star })}
                    onMouseEnter={() => setHoverRating(star)}
                    onMouseLeave={() => setHoverRating(0)}
                    className="focus:outline-none transition-transform active:scale-95"
                  >
                    <Star 
                      className={`w-6 h-6 ${
                        star <= (hoverRating || feedbackForm.rating) 
                          ? 'fill-amber-400 text-amber-400' 
                          : 'text-slate-200'
                      }`} 
                    />
                  </button>
                ))}
              </div>
            </div>

            {/* Experience Dropdown */}
            <div>
              <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest block mb-1.5">Experience Quality</label>
              <select
                value={feedbackForm.experience}
                onChange={(e) => setFeedbackForm({ ...feedbackForm, experience: e.target.value })}
                className="w-full bg-white border border-slate-200 rounded-xl px-4 py-2 text-xs font-bold focus:outline-none focus:border-[#6D5DFC] cursor-pointer"
              >
                <option value="Excellent">Excellent</option>
                <option value="Good">Good</option>
                <option value="Average">Average</option>
                <option value="Below Average">Below Average</option>
              </select>
            </div>

            {/* Comment box */}
            <div>
              <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest block mb-1.5">Comments / Reviews</label>
              <textarea
                placeholder="Share your thoughts about using AI LEGAL..."
                rows={3}
                value={feedbackForm.comment}
                onChange={(e) => setFeedbackForm({ ...feedbackForm, comment: e.target.value })}
                className="w-full bg-white border border-slate-200 rounded-xl px-4 py-2.5 text-xs font-bold focus:outline-none focus:border-[#6D5DFC] resize-none placeholder-slate-400"
              />
            </div>

            {/* Submit */}
            <button
              type="submit"
              className="w-full py-2.5 bg-[#6D5DFC] hover:bg-[#5b4edb] text-white rounded-xl text-xs font-black uppercase tracking-wider transition-colors shadow-lg shadow-[#6D5DFC]/10"
            >
              Submit Feedback
            </button>
          </form>
        </section>
      </div>

      {/* Grid for Bug & Feature Requests */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        
        {/* 3. Report a Bug */}
        <section className="space-y-6">
          <div className="flex items-center gap-2">
            <Bug className="w-5 h-5 text-[#6D5DFC]" />
            <div>
              <h2 className="text-sm font-black uppercase tracking-widest text-[#6D5DFC] mb-0.5">Report a Bug</h2>
              <p className="text-xs font-semibold text-slate-400">Encountered an issue? Tell our engineers.</p>
            </div>
          </div>

          <form onSubmit={handleBugSubmit} className="p-6 border border-slate-100 rounded-2xl space-y-4 bg-white">
            {/* Title */}
            <div>
              <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest block mb-1.5">Bug Title</label>
              <input
                type="text"
                placeholder="e.g. Draft creator fails on PDF download"
                value={bugForm.title}
                onChange={(e) => setBugForm({ ...bugForm, title: e.target.value })}
                className="w-full bg-white border border-slate-200 rounded-xl px-4 py-2 text-xs font-bold focus:outline-none focus:border-[#6D5DFC] placeholder-slate-400"
              />
            </div>

            {/* Description */}
            <div>
              <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest block mb-1.5">Description</label>
              <textarea
                placeholder="Describe what went wrong and how to reproduce it..."
                rows={3}
                value={bugForm.description}
                onChange={(e) => setBugForm({ ...bugForm, description: e.target.value })}
                className="w-full bg-white border border-slate-200 rounded-xl px-4 py-2.5 text-xs font-bold focus:outline-none focus:border-[#6D5DFC] resize-none placeholder-slate-400"
              />
            </div>

            {/* Screenshot Upload */}
            <div>
              <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest block mb-1.5">Screenshot Attachment</label>
              <label className="w-full flex items-center gap-3 border border-slate-200 rounded-xl px-4 py-2 text-xs font-bold bg-slate-50 hover:bg-slate-100 text-slate-500 transition-colors cursor-pointer justify-center">
                <span>Attach Screenshot (PNG, JPG)</span>
                <input 
                  type="file" 
                  accept="image/*"
                  onChange={handleFileChange}
                  className="hidden" 
                />
              </label>
              {bugForm.screenshot && (
                <p className="text-[10px] font-bold text-[#6D5DFC] mt-1.5 truncate">Attached: {bugForm.screenshot.name}</p>
              )}
            </div>

            {/* Auto-filled details */}
            <div className="grid grid-cols-2 gap-3 pt-2">
              <div>
                <label className="text-[8px] font-black text-slate-400 uppercase tracking-widest block mb-0.5">Current Page</label>
                <input
                  type="text"
                  readOnly
                  value={currentPage}
                  title={currentPage}
                  className="w-full bg-slate-50 border border-slate-100 rounded-lg px-2.5 py-1.5 text-[10px] font-semibold text-slate-400 outline-none truncate"
                />
              </div>
              <div>
                <label className="text-[8px] font-black text-slate-400 uppercase tracking-widest block mb-0.5">Detected Device</label>
                <input
                  type="text"
                  readOnly
                  value={browserInfo}
                  title={browserInfo}
                  className="w-full bg-slate-50 border border-slate-100 rounded-lg px-2.5 py-1.5 text-[10px] font-semibold text-slate-400 outline-none truncate"
                />
              </div>
            </div>

            {/* Submit */}
            <button
              type="submit"
              className="w-full py-2.5 bg-[#6D5DFC] hover:bg-[#5b4edb] text-white rounded-xl text-xs font-black uppercase tracking-wider transition-colors shadow-lg shadow-[#6D5DFC]/10"
            >
              Submit Bug Report
            </button>
          </form>
        </section>

        {/* 4. Request a Feature */}
        <section className="space-y-6">
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-[#6D5DFC]" />
            <div>
              <h2 className="text-sm font-black uppercase tracking-widest text-[#6D5DFC] mb-0.5">Request a Feature</h2>
              <p className="text-xs font-semibold text-slate-400">Suggest product ideas to our team.</p>
            </div>
          </div>

          <form onSubmit={handleFeatureSubmit} className="p-6 border border-slate-100 rounded-2xl space-y-4 bg-white">
            {/* Title */}
            <div>
              <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest block mb-1.5">Feature Title</label>
              <input
                type="text"
                placeholder="e.g. Direct integrations with High Court logs"
                value={featureForm.title}
                onChange={(e) => setFeatureForm({ ...featureForm, title: e.target.value })}
                className="w-full bg-white border border-slate-200 rounded-xl px-4 py-2 text-xs font-bold focus:outline-none focus:border-[#6D5DFC] placeholder-slate-400"
              />
            </div>

            {/* Description */}
            <div>
              <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest block mb-1.5">Description</label>
              <textarea
                placeholder="Describe the feature you want in detail..."
                rows={3}
                value={featureForm.description}
                onChange={(e) => setFeatureForm({ ...featureForm, description: e.target.value })}
                className="w-full bg-white border border-slate-200 rounded-xl px-4 py-2.5 text-xs font-bold focus:outline-none focus:border-[#6D5DFC] resize-none placeholder-slate-400"
              />
            </div>

            {/* Expected Benefit */}
            <div>
              <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest block mb-1.5">Expected Benefit</label>
              <textarea
                placeholder="Explain how this feature will benefit advocates..."
                rows={2}
                value={featureForm.benefit}
                onChange={(e) => setFeatureForm({ ...featureForm, benefit: e.target.value })}
                className="w-full bg-white border border-slate-200 rounded-xl px-4 py-2.5 text-xs font-bold focus:outline-none focus:border-[#6D5DFC] resize-none placeholder-slate-400"
              />
            </div>

            {/* Submit */}
            <button
              type="submit"
              className="w-full py-2.5 bg-[#6D5DFC] hover:bg-[#5b4edb] text-white rounded-xl text-xs font-black uppercase tracking-wider transition-colors shadow-lg shadow-[#6D5DFC]/10"
            >
              Submit Request
            </button>
          </form>
        </section>
      </div>

      {/* Footer Details: 6. Legal Policies & 7. About AI LEGAL */}
      <footer className="border-t border-slate-100 pt-8 flex flex-col sm:flex-row items-center sm:items-start justify-between gap-6">
        
        {/* Legal Policies */}
        <div className="space-y-2 text-center sm:text-left">
          <span className="text-[9px] font-black uppercase tracking-widest text-[#6D5DFC] block">Legal & Privacy Policies</span>
          <div className="flex items-center gap-4 text-xs font-bold text-[#6D5DFC]">
            <Link to="/privacy-policy" className="hover:underline">Privacy Policy</Link>
            <span className="text-slate-300">•</span>
            <Link to="/terms-of-service" className="hover:underline">Terms & Conditions</Link>
            <span className="text-slate-300">•</span>
            <a href="https://support.ai-legal.in/cookies" target="_blank" rel="noopener noreferrer" className="hover:underline">Cookie Policy</a>
          </div>
        </div>

        {/* About AI LEGAL */}
        <div className="text-center sm:text-right space-y-1">
          <span className="text-xs font-extrabold text-slate-700 block">AI LEGAL™</span>
          <span className="text-[10px] font-semibold text-slate-400 block">Advocate Edition</span>
          <span className="text-[10px] font-semibold text-slate-400 block">Version 1.2.0</span>
          <span className="text-[9px] font-semibold text-slate-400 block">© 2026 AI Legal™</span>
        </div>

      </footer>

    </div>
  );
};

export default HelpSupport;
